### ISSUE TITLE
[1.11.2]Alchemy Table tries to nullify a null object

### ISSUE THREAD

**Issue by Yoghurt4C** [WayofTime/BloodMagic#1082]
#### Issue Description:
Alchemy Table tries to nullify a null object

#### What happens:
When you're using the alchemy table with cutting fluid and it's at 1/16 uses, the moment the operation ends the server crashes

Log cutout:
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at WayofTime.bloodmagic.tile.TileInventory.func_70299_a(TileInventory.java:150)
	at WayofTime.bloodmagic.tile.TileAlchemyTable.consumeInventory(TileAlchemyTable.java:398)
	at WayofTime.bloodmagic.tile.TileAlchemyTable.craftItem(TileAlchemyTable.java:364)
	at WayofTime.bloodmagic.tile.TileAlchemyTable.func_73660_a(TileAlchemyTable.java:258)

#### What you expected to happen:
For the null fluid to disappear without producing a crash

#### Steps to reproduce:

1. Put something along with a 1/16 damaged cutting fluid in an alchemy table
2. Wait for it to finish the process
3. Crash

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: gradle build from 3rd of march 2017 (a couple of hours before this issue surfacing)
- Minecraft: 1.11.2
- Forge: 13.20.0.2252

**Comment by TehNut** [comment]
If you're reporting something with a custom build, I need the actual commit it was built from. I also need the full log. Not what you think is useful.

**Comment by Yoghurt4C** [comment]
Should be 4e5bc46e21e99adc4c460bf99f8387ad295c7ce3. 
http://pastebin.com/AqV3dCMt
