### ISSUE TITLE
[1.11.2][1.11-2.15-74]NPE While Ticking Player

### ISSUE THREAD

**Issue by gudenau** [WayofTime/BloodMagic#1084]
#### Issue Description:
When I dropped a will on the ground and picked it up with a basic gem in my inventory the PlayerDemonWillHandler throws a NPE in addDemonWill. This causes my player to get kicked and I am unable to rejoin the server.

Here is the stack trace plus what comes right before and after on the dedicated server:
```
[14:41:18] [Server thread/WARN]: Failed to handle packet for /45.26.83.131:50926
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:406) ~[ly.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164) ~[mi.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[er.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at WayofTime.bloodmagic.api.soul.PlayerDemonWillHandler.addDemonWill(PlayerDemonWillHandler.java:148) ~[PlayerDemonWillHandler.class:1.11-2.1.5-74]
	at WayofTime.bloodmagic.util.handler.event.WillHandler.onItemPickup(WillHandler.java:55) ~[WillHandler.class:1.11-2.1.5-74]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_WillHandler_onItemPickup_EntityItemPickupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:415) ~[ForgeEventFactory.class:?]
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:395) ~[zj.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:582) ~[aay.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:574) ~[aay.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085) ~[sw.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) ~[aay.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329) ~[ly.class:?]
	... 9 more
[14:41:18] [Server thread/INFO]: gudenau lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
```

And the stack crash report on the client when in a single player world:
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.10.jar)
  GudLib (gud_lib-1.1.0.2.jar)
  Plugin (ExtraUtilsFix-1.0.jar)
  OpenEyePlugin (OpenEye-1.11.2-0.8.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  LoadingPlugin (ResourceLoader-MC1.11-1.5.1.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  LoadingPlugin (Quark-r1.2-83.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.12r.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 3/6/17 1:49 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at WayofTime.bloodmagic.api.soul.PlayerDemonWillHandler.addDemonWill(PlayerDemonWillHandler.java:148)
	at WayofTime.bloodmagic.util.handler.event.WillHandler.onItemPickup(WillHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_224_WillHandler_onItemPickup_EntityItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:415)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:395)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:582)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:574)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at WayofTime.bloodmagic.api.soul.PlayerDemonWillHandler.addDemonWill(PlayerDemonWillHandler.java:148)
	at WayofTime.bloodmagic.util.handler.event.WillHandler.onItemPickup(WillHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_224_WillHandler_onItemPickup_EntityItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:415)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:395)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:582)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:574)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 557
	Entity Name: gudenau
	Entity's Exact location: -162.71, 90.00, 186.56
	Entity's Block location: World: (-163,90,186), Chunk: (at 13,5,10 in -11,11; contains blocks -176,0,176 to -161,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@7b0787c5
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2374372352 bytes (2264 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 12 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx6144m -Xms6144m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2252 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2252.jar) 
	UCHIJAAAA	forge{13.20.0.2252} [Minecraft Forge] (forge-1.11.2-13.20.0.2252.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	gud_lib{1.0.0.1} [GudLib] (gud_lib-1.1.0.2.jar) 
	UCHIJAAAA	OpenEye{0.8} [OpenEye] (OpenEye-1.11.2-0.8.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r103} [Actually Additions] (ActuallyAdditions-1.11.2-r103.jar) 
	UCHIJAAAA	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCHIJAAAA	psi{r1.1-46} [Psi] (Psi-r1.1-46.jar) 
	UCHIJAAAA	quark{r1.2-83} [Quark] (Quark-r1.2-83.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	bdlib{1.13.1.5} [BD Lib] (bdlib-1.13.1.5-mc1.11.2.jar) 
	UCHIJAAAA	betterachievements{0.4.3.12} [Better Achievements] (BetterAchievements-1.11.2-0.4.3.12.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.0} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.0.233+4d933ac.jar) 
	UCHIJAAAA	biomesoplenty{6.0.2.2164} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2164-universal.jar) 
	UCHIJAAAA	guideapi{1.11-2.1.0-50} [Guide-API] (Guide-API-1.11-2.1.0-50.jar) 
	UCHIJAAAA	bloodmagic{1.11-2.1.5-74} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.5-74.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.9.10} [Chisel] (Chisel-MC1.11.2-0.0.9.10.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	cyclopscore{0.9.3} [Cyclops Core] (CyclopsCore-1.11.2-0.9.3.jar) 
	UCHIJAAAA	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.11.2-1.5.0.jar) 
	UCHIJAAAA	controlling{2.0.4} [Controlling] (Controlling-2.0.4.jar) 
	UCHIJAAAA	custombackgrounds{1.0} [Custom Backgrounds] (CustomBackgrounds-MC1.11-1.1.jar) 
	UCHIJAAAA	custommainmenu{2.0.3} [Custom Main Menu] (CustomMainMenu-MC1.11-2.0.3.jar) 
	UCHIJAAAA	forestry{5.3.1.45} [Forestry] (forestry_1.11.2-5.3.1.45.jar) 
	UCHIJAAAA	eleccore{1.7.409} [ElecCore] (ElecCore-1.11-1.7.409.jar) 
	UCHIJAAAA	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCHIJAAAA	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHIJAAAA	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.0.jar) 
	UCHIJAAAA	zerocore{1.11.2-0.1.0.4} [Zero CORE] (zerocore-1.11.2-0.1.0.4.jar) 
	UCHIJAAAA	bigreactors{1.11.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.27.jar) 
	UCHIJAAAA	fastleavedecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.11-1.2.3.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.1-anarchy.jar) 
	UCHIJAAAA	gendustry{1.6.5.5} [GenDustry] (gendustry-1.6.5.5-mc1.11.2.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	gud_clear_jukebox{1.0.0.1} [Clear Jukebox] (gud_clear_jukebox-1.0.0.1.jar) 
	UCHIJAAAA	gud_coolers{2.0.0.4} [Coolers] (gud_coolers-2.0.0.4.jar) 
	UCHIJAAAA	hammercore{1.2.8} [Hammer Core] (HammerCore_1.11.2-1.2.8.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-77-7812cce} [Inventory Tweaks] (InventoryTweaks-1.62-dev-77.jar) 
	UCHIJAAAA	jei{4.2.7.241} [Just Enough Items] (jei_1.11.2-4.2.7.241.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	jeresources{0.6.3.4} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.3.4.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	mercurius{1.0.1} [Mercurius] (Mercurius-1.11.2-1.0.2.jar) 
	UCHIJAAAA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.2} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.2.jar) 
	UCHIJAAAA	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCHIJAAAA	harvestcraft{1.11.2d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2d.jar) 
	UCHIJAAAA	randomthings{3.8} [Random Things] (RandomThings-MC1.11.2-3.8.jar) 
	UCHIJAAAA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJAAAA	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCHIJAAAA	resourceloader{1.5.1} [Resource Loader] (ResourceLoader-MC1.11-1.5.1.jar) 
	UCHIJAAAA	rftools{5.85} [RFTools] (rftools-1.1x-5.85.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHIJAAAA	rftoolsdim{4.54} [RFTools Dimensions] (rftoolsdim-1.1x-4.54.jar) 
	UCHIJAAAA	roots{0.010} [Roots 2] (roots-2-0.011.jar) 
	UCHIJAAAA	solarfluxreborn{2.12r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.12r.jar) 
	UCHIJAAAA	soulshardstow{1.11-2.6.6-47} [Soul Shards - The Old Ways] (SoulShards-TOW-1.11-2.6.6-47.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	UCHIJAAAA	theoneprobe{1.4.4} [The One Probe] (theoneprobe-1.1x-1.4.4.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	xtones{1.11-1.0.1-3} [Xtones] (Xtones-1.11-1.0.1-3.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  invtweaks.forge.asm.ContainerTransformer
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.10.jar)
  team.chisel.common.asm.ChiselTransformer
GudLib (gud_lib-1.1.0.2.jar)
  net.gudenau.lib.core.ClientTransformer
Plugin (ExtraUtilsFix-1.0.jar)
  net.gudenau.euf.Transformer
OpenEyePlugin (OpenEye-1.11.2-0.8.jar)
  openeye.asm.MultiTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  lumien.randomthings.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.11-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
LoadingPlugin (Quark-r1.2-83.jar)
  vazkii.quark.base.asm.ClassTransformer
SFRCore (SolarFluxReborn_1.11.2-2.12r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r103.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.11-2.1.0.0.b64.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* BetterAchievements|API (0.4.3.12) from BetterAchievements-1.11.2-0.4.3.12.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.11.2-0.4.5.27.jar
		* bloodmagic|API (1.11-2.1.5-74) from BloodMagic-1.11-2.1.5-74.jar
		* BotaniaAPI (79) from AkashicTome-1.1-7.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.9.10.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.9.10.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
		* CoFHAPI (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.9.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.9.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* compatlayer (0.2.2) from compatlayer-1.11.2-0.2.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.6.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.409.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.409.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.1.45.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.1.45.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.5-mc1.11.2.jar
		* gud_coolers (1.0.1) from gud_coolers-2.0.0.4.jar
		* Guide-API|API (1.11-2.1.0-50) from Guide-API-1.11-2.1.0-50.jar
		* jeresources|API (0.6.3.4) from JustEnoughResources-1.11.2-0.6.3.4.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.7.241.jar
		* mcjtylib_ng (2.3.9) from mcjtylib-1.1x-2.3.9.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.11.2.jar
		* PsiAPI (4) from Psi-r1.1-46.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.4.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
		* WailaAPI (1.3) from Hwyla-1.8.10-B23_1.11.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['gudenau'/557, l='Creative', x=-162.71, y=90.00, z=186.56]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

#### What happens:
A NPE is thrown and my player is kicked, preventing me from logging into the server.

#### What you expected to happen:
The gem to absorb the will.

#### Steps to reproduce:

1. Craft a gem
2. Toss a will
3. Pick up the will
4. Crash

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.15-74
- Minecraft: 1.11.2
- Forge: 13.20.0.2252

**Comment by Gayanfalor** [comment]
Hello, i think its the same problem as the #1068 
if you play in multiplayer ask some one to get where you was and get the gem and you'll can rejoin

**Comment by gudenau** [comment]
I did not see that, my mistake.
