### ISSUE TITLE
No mroe loot with sentient sword. (BloodMagic-1.11-2.1.6-75)

### ISSUE THREAD

**Issue by Kelgram** [WayofTime/BloodMagic#1097]
Hey there!
I do not get any drops from monsters if I kill them with the sentient sword (it's enchanted with looting3, smite4 and unbreaking2). A few hours ago, it worked perfectly but since then, i get nothing else but XP and demon Will. This occurs on my Server with some other mods (namely Embers and Roots) but on a singleplayer map with the same modset, i still get drops (so I doubt this a problem between the mods). If I give my sword to another player on the server, he can get drops with my sword, just like I did a few hours ago. If I try a vanilla sword, I get drops. With another sentient sword (enchanted and unenchanted), I get no loot. I tried to delete my playerdata from the world, but that did nothing to this issue.

Checking the server-log showed, that there is a problem. Here is one of the error messages:
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to WayofTime.bloodmagic.api.soul.IDemonWill
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

The mod version is BloodMagic-1.11-2.1.6-75, I updated the server yesterday and after the update, it worked until now.
I hope you can help me out, I'm a bit confused about this problem. 

Kind regards,
Kelgram

**Comment by TehNut** [comment]
#1091
