### ISSUE TITLE
Index out of bounds exception when generating dungeons.

### ISSUE THREAD

**Issue by ckchessmaster** [WayofTime/BloodMagic#1135]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

I'm using a custom modpack that I put together so if you can't help that's fine but basically whenever the mod monstersanddungeons creates a dungeon I get this error:
`Exception ticking world java.lang.ArrayIndexOutOfBoundsException: 3
	at WayofTime.bloodmagic.block.base.BlockEnum.func_176203_a(BlockEnum.java:55)
	at net.minecraft.block.Block.func_176220_d(Block.java:96)
	at monstersanddungeons.util.dungeon.DungeonRoom.loadRoom(DungeonRoom.java:252)
	at monstersanddungeons.util.dungeon.Dungeon.createBranch(Dungeon.java:67)
	at monstersanddungeons.world.dungeons.DungeonAutomatons.ConstructDungeon(DungeonAutomatons.java:81)
	at monstersanddungeons.world.MaDWorldGenerationHandler.generate(MaDWorldGenerationHandler.java:34)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

`
#### Steps to reproduce:

1. Install and use monstersanddungeons
2. Walk around until a dungeon is spawned
3. crash

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.9-78
- Minecraft: 1.10.2
- Forge: 12.18.3.2185-universal

**Comment by TehNut** [comment]
That mod is trying to load an invalid state from us.

**Comment by ckchessmaster** [comment]
Thanks for the info! I'll pass this information on to them.
