### ISSUE TITLE
Blood Sigil Crash

### ISSUE THREAD

**Issue by SnowMntGaming** [WayofTime/BloodMagic#1262]
#### Issue Description:
Time: 4/2/18 11:09 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at WayofTime.bloodmagic.util.helper.NetworkHelper.getSoulNetwork(NetworkHelper.java:63)
	at WayofTime.bloodmagic.item.sigil.ItemSigilBloodLight.func_77659_a(ItemSigilBloodLight.java:45)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1595)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Head --
Thread: Client thread
Stacktrace:
	at WayofTime.bloodmagic.util.helper.NetworkHelper.getSoulNetwork(NetworkHelper.java:63)
	at WayofTime.bloodmagic.item.sigil.ItemSigilBloodLight.func_77659_a(ItemSigilBloodLight.java:45)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1595)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

#### Steps to reproduce:

1. Craft a blood lamp sigil
2. Use blood lamp sigil
3. Crash and suffer
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.7-90
- Minecraft: 1.12.2
- Forge: 14.23.2.2635

**Comment by TehNut** [comment]
#1243
