### ISSUE TITLE
Blood magic 1.7.10 crashes server on placement

### ISSUE THREAD

**Issue by kiefernobody** [WayofTime/BloodMagic#1298]
#### Issue Description:
Every time I place my blood altar it works for about 10-15 seconds then it crashes and says server closed. Then I have to open the server and run as quick as I can to the altar before it crashes as it gives me about 5 seconds for next crash. Breaking altar fixes it.
The server is hosted on my computer

#### What happens:
It says server closed when Altar is placed.

#### What you expected to happen:
Altar is placed and is usable for the mods use without server crash.

#### Steps to reproduce:

1. Make blood altar
2. Place blood altar
3. Wait 20 seconds
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.3.3
- Minecraft: 1.7.10
- Forge: 1558

**Comment by TehNut** [comment]
...And the log is?

**Comment by kiefernobody** [comment]
[21:59:09] [Server thread/INFO]: Starting minecraft server version 1.7.10
[21:59:32] [Server thread/INFO]: Loading properties
[21:59:32] [Server thread/INFO]: Default game type: SURVIVAL
[21:59:32] [Server thread/INFO]: Generating keypair
[21:59:32] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:59:38] [Server thread/INFO]: Preparing level "world"
[21:59:40] [Server thread/INFO]: Preparing start region for level 0
[21:59:41] [Server thread/INFO]: Done (2.607s)! For help, type "help" or "?"
[21:59:45] [User Authenticator #1/INFO]: UUID of player Atlas_Kiefer is d70369ae-654d-43ef-af3a-f7dd82734b9c
[21:59:45] [Server thread/INFO]: Atlas_Kiefer[/173.69.143.99:1025] logged in with entity id 895 at (537.5242931686914, 63.0, -458.38194422674025)
[21:59:45] [Server thread/INFO]: Atlas_Kiefer joined the game
[22:04:19] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: com/cricketcraft/chisel/api/carving/CarvingUtils
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.CompatChecks.checkChiselBlock(CompatChecks.java:14) ~[CompatChecks.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkRuneSpecials(UpgradedAltars.java:365) ~[UpgradedAltars.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkAltarIsValid(UpgradedAltars.java:171) ~[UpgradedAltars.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.isAltarValid(UpgradedAltars.java:34) ~[UpgradedAltars.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.checkAndSetAltar(TEAltar.java:763) ~[TEAltar.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.startCycle(TEAltar.java:734) ~[TEAltar.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145845_h(TEAltar.java:528) ~[TEAltar.class:1.7.10-1.3.3-17]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.cricketcraft.chisel.api.carving.CarvingUtils
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.CompatChecks.checkChiselBlock(CompatChecks.java:14) ~[CompatChecks.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkRuneSpecials(UpgradedAltars.java:365) ~[UpgradedAltars.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkAltarIsValid(UpgradedAltars.java:171) ~[UpgradedAltars.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.isAltarValid(UpgradedAltars.java:34) ~[UpgradedAltars.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.checkAndSetAltar(TEAltar.java:763) ~[TEAltar.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.startCycle(TEAltar.java:734) ~[TEAltar.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145845_h(TEAltar.java:528) ~[TEAltar.class:1.7.10-1.3.3-17]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.NullPointerException
[22:04:20] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Kiefer\AppData\Roaming\.minecraft\server\.\crash-reports\crash-2018-05-04_22.04.19-server.txt
[22:04:20] [Server thread/INFO]: Stopping server
[22:04:20] [Server thread/INFO]: Saving players
[22:04:20] [Server thread/INFO]: Saving worlds
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/The End
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Space
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Phantom Zone
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Dimension-Chaos
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Dimension-Crystal
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Dimension-Islands
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Dimension-VillageMania
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Dimension-Extreme
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Dimension-Utopia
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Quantum Realm
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Spirit World
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Torment
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Mirror
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Underdark
[22:04:20] [Server thread/INFO]: Saving chunks for level 'world'/Twilight Forest
[22:04:21] [Server thread/INFO]: Saving chunks for level 'world'/The Last Millenium

**Comment by TehNut** [comment]
Sorry, we're not accepting issues for 1.7.10, anymore!
