### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by kmork1** [WayofTime/BloodMagic#1335]
#### Issue Description:
activating ritual of magentism after its done

#### What happens:

Time: 5/30/18 10:46 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cofh.thermaldynamics.block.BlockDuct.getPickBlock(BlockDuct.java:288)
	at WayofTime.bloodmagic.ritual.types.RitualMagnetic.performRitual(RitualMagnetic.java:71)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:187)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:67)
	at WayofTime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:18)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cofh.thermaldynamics.block.BlockDuct.getPickBlock(BlockDuct.java:288)
	at WayofTime.bloodmagic.ritual.types.RitualMagnetic.performRitual(RitualMagnetic.java:71)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:187)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:67)
	at WayofTime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:18)

-- Block entity being ticked --
Details:
	Name: bloodmagic:master_ritual_stone // WayofTime.bloodmagic.tile.TileMasterRitualStone
	Block type: ID #1401 (tile.bloodmagic.stone.ritual. // WayofTime.bloodmagic.block.BlockRitualController)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (376,63,302), Chunk: (at 8,3,14 in 23,18; contains blocks 368,0,288 to 383,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1401 (tile.bloodmagic.stone.ritual. // WayofTime.bloodmagic.block.BlockRitualController)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['KimMorkII'/320, l='New World', x=377.22, y=64.00, z=301.95]]
	Chunk stats: ServerChunkCache: 458 Drop: 0
	Level seed: -7666165388260452997
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (136,64,248), Chunk: (at 8,4,8 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 932201 game time, 1065336 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 152813 (now: false), thunder time: 106163 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.5
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 593919032 bytes (566 MB) / 3758620672 bytes (3584 MB) up to 5965348864 bytes (5689 MB)
	JVM Flags: 3 total; -Xmx6400m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2691 168 mods loaded, 168 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

#### What you expected to happen:
nothing

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft: 1.12
- Forge: 14.23.3.2691

**Comment by kmork1** [comment]
Just had the issue again but this time it was when it finished getting all the available ore in the area it can reach. I'm using a diamond block under the master stone
