### ISSUE TITLE
Crash while opening page Burning Furnace Array of the Sanguine Scientiem

### ISSUE THREAD

**Issue by YetAnotherSimon** [WayofTime/BloodMagic#1373]
#### Issue Description:
The game crashes.

#### What happens:
After opening the page Burning Furnace Array the game crashes frequently. Reproduced on several OS.

#### What you expected to happen:
No crash. (In some cases the page has opened, but in most cases not).

#### Steps to reproduce:

1. Open game with JEI, Guide-API and BloodMagic
2. Get a Sanguine Scientiem
3. Open the first chapter
4. Open Burning Furnace Array

____
#### Affected Versions:

- BloodMagic: 2.3.1-99
- Minecraft: 1.12.2
- Forge: 14.23.4.2705; 14.23.4.2739

#### Crash report:
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/23/18 2:21 PM
Description: Rendering screen

java.lang.IllegalAccessError: tried to access method net.minecraft.client.gui.GuiScreen.func_146285_a(Lnet/minecraft/item/ItemStack;II)V from class WayofTime.bloodmagic.compat.guideapi.page.PageAlchemyArray
	at WayofTime.bloodmagic.compat.guideapi.page.PageAlchemyArray.draw(PageAlchemyArray.java:77)
	at amerifrance.guideapi.wrapper.PageWrapper.draw(PageWrapper.java:50)
	at amerifrance.guideapi.gui.GuiEntry.func_73863_a(GuiEntry.java:82)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at WayofTime.bloodmagic.compat.guideapi.page.PageAlchemyArray.draw(PageAlchemyArray.java:77)
	at amerifrance.guideapi.wrapper.PageWrapper.draw(PageWrapper.java:50)
	at amerifrance.guideapi.gui.GuiEntry.func_73863_a(GuiEntry.java:82)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: amerifrance.guideapi.gui.GuiEntry
	Mouse location: Scaled: (213, 78). Absolute: (851, 711)
	Screen size: Scaled: (464, 257). Absolute: (1853, 1025). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP[''/870, l='MpServer', x=738.50, y=63.00, z=105.50]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (739,64,101), Chunk: (at 3,4,5 in 46,6; contains blocks 736,0,96 to 751,255,111), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 651 game time, 651 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 76 total; [EntityChicken['Chicken'/8, l='MpServer', x=748.84, y=67.00, z=64.40], EntityChicken['Chicken'/9, l='MpServer', x=750.50, y=68.00, z=69.50], EntityChicken['Chicken'/10, l='MpServer', x=751.50, y=68.00, z=71.50], EntityChicken['Chicken'/11, l='MpServer', x=751.50, y=68.00, z=71.50], EntitySkeleton['Skeleton'/2062, l='MpServer', x=776.50, y=30.00, z=134.50], EntityChicken['Chicken'/16, l='MpServer', x=769.50, y=67.00, z=73.50], EntityChicken['Chicken'/17, l='MpServer', x=770.50, y=67.00, z=74.50], EntityChicken['Chicken'/18, l='MpServer', x=771.50, y=67.00, z=74.50], EntityChicken['Chicken'/19, l='MpServer', x=772.50, y=67.00, z=73.50], EntityPig['Pig'/20, l='MpServer', x=760.76, y=68.00, z=76.97], EntityPig['Pig'/21, l='MpServer', x=763.50, y=67.00, z=74.50], EntityPig['Pig'/22, l='MpServer', x=755.65, y=68.00, z=67.77], EntityPig['Pig'/23, l='MpServer', x=760.50, y=68.00, z=73.50], EntitySkeleton['Skeleton'/4119, l='MpServer', x=744.50, y=27.00, z=111.50], EntityPig['Pig'/24, l='MpServer', x=773.30, y=67.00, z=73.65], EntityZombie['Zombie'/4120, l='MpServer', x=747.50, y=27.00, z=113.50], EntityPig['Pig'/25, l='MpServer', x=772.76, y=67.00, z=70.77], EntityPig['Pig'/26, l='MpServer', x=773.50, y=67.00, z=77.50], EntityPig['Pig'/27, l='MpServer', x=772.50, y=67.00, z=78.50], EntityChicken['Chicken'/30, l='MpServer', x=779.88, y=67.00, z=72.51], EntityChicken['Chicken'/31, l='MpServer', x=788.50, y=66.00, z=62.50], EntityChicken['Chicken'/32, l='MpServer', x=787.50, y=66.00, z=62.50], EntityChicken['Chicken'/33, l='MpServer', x=779.80, y=66.00, z=68.08], EntityChicken['Chicken'/34, l='MpServer', x=784.50, y=67.00, z=86.50], EntityChicken['Chicken'/35, l='MpServer', x=785.50, y=67.00, z=85.50], EntityChicken['Chicken'/36, l='MpServer', x=784.50, y=67.00, z=86.50], EntityChicken['Chicken'/37, l='MpServer', x=781.50, y=68.00, z=85.50], EntityZombie['Zombie'/4203, l='MpServer', x=722.50, y=20.00, z=52.50], EntitySkeleton['Skeleton'/4208, l='MpServer', x=661.50, y=26.00, z=174.50], EntitySpider['Spider'/4242, l='MpServer', x=768.50, y=42.00, z=103.50], EntityCreeper['Creeper'/4244, l='MpServer', x=765.79, y=41.00, z=97.59], EntityCreeper['Creeper'/4245, l='MpServer', x=770.62, y=42.00, z=102.30], EntityCreeper['Creeper'/4282, l='MpServer', x=658.50, y=28.00, z=170.50], EntityBat['Bat'/4344, l='MpServer', x=663.32, y=23.03, z=163.53], EntityCreeper['Creeper'/4369, l='MpServer', x=676.50, y=24.00, z=107.50], EntityCreeper['Creeper'/4430, l='MpServer', x=779.50, y=32.00, z=27.50], EntityZombie['Zombie'/3072, l='MpServer', x=781.50, y=32.00, z=33.50], EntityPlayerSP[''/870, l='MpServer', x=738.50, y=63.00, z=105.50], EntitySkeleton['Skeleton'/3439, l='MpServer', x=762.50, y=36.00, z=139.50], EntityCreeper['Creeper'/3545, l='MpServer', x=702.50, y=57.00, z=43.50], EntityCreeper['Creeper'/3546, l='MpServer', x=704.46, y=58.00, z=41.83], EntityZombie['Zombie'/3547, l='MpServer', x=701.50, y=57.00, z=45.50], EntitySkeleton['Skeleton'/3610, l='MpServer', x=778.70, y=31.00, z=134.53], EntitySkeleton['Skeleton'/3611, l='MpServer', x=782.50, y=30.00, z=137.50], EntityCreeper['Creeper'/3612, l='MpServer', x=786.50, y=30.00, z=134.50], EntityCreeper['Creeper'/3613, l='MpServer', x=782.59, y=29.00, z=134.80], EntityBat['Bat'/3615, l='MpServer', x=674.63, y=40.46, z=28.70], EntityBat['Bat'/3617, l='MpServer', x=682.37, y=40.17, z=23.79], EntityBat['Bat'/3619, l='MpServer', x=712.06, y=36.72, z=30.96], EntityBat['Bat'/3706, l='MpServer', x=681.86, y=15.76, z=156.20], EntitySkeleton['Skeleton'/3748, l='MpServer', x=670.50, y=26.00, z=107.50], EntitySpider['Spider'/3784, l='MpServer', x=780.50, y=15.00, z=73.50], EntitySkeleton['Skeleton'/3785, l='MpServer', x=745.50, y=28.00, z=105.50], EntityBat['Bat'/3798, l='MpServer', x=689.32, y=11.42, z=135.62], EntityZombie['Zombie'/3849, l='MpServer', x=800.50, y=26.00, z=170.74], EntityZombie['Zombie'/3850, l='MpServer', x=801.50, y=25.00, z=176.50], EntitySquid['Squid'/1807, l='MpServer', x=752.05, y=55.14, z=168.94], EntitySquid['Squid'/1808, l='MpServer', x=757.18, y=53.07, z=167.87], EntitySquid['Squid'/1834, l='MpServer', x=675.71, y=59.64, z=65.57], EntitySquid['Squid'/1838, l='MpServer', x=680.39, y=62.46, z=61.14], EntitySquid['Squid'/1844, l='MpServer', x=684.77, y=61.04, z=137.69], EntitySquid['Squid'/1845, l='MpServer', x=687.72, y=62.42, z=133.04], EntitySquid['Squid'/1847, l='MpServer', x=681.60, y=59.86, z=131.06], EntitySquid['Squid'/1848, l='MpServer', x=730.00, y=46.78, z=150.11], EntitySquid['Squid'/1849, l='MpServer', x=724.77, y=47.60, z=139.49], EntitySquid['Squid'/1850, l='MpServer', x=734.63, y=47.00, z=145.18], EntitySquid['Squid'/1851, l='MpServer', x=736.60, y=45.79, z=155.02], EntitySquid['Squid'/1853, l='MpServer', x=688.81, y=51.23, z=130.73], EntitySquid['Squid'/1855, l='MpServer', x=689.62, y=54.42, z=136.01], EntitySquid['Squid'/1856, l='MpServer', x=692.01, y=51.90, z=136.54], EntityBat['Bat'/3992, l='MpServer', x=693.94, y=15.46, z=162.62], EntityBat['Bat'/3993, l='MpServer', x=679.66, y=27.10, z=158.70], EntityBat['Bat'/4022, l='MpServer', x=663.10, y=28.79, z=105.65], EntityBat['Bat'/4069, l='MpServer', x=754.88, y=23.10, z=94.55], EntityZombieVillager['Zombie Villager'/4078, l='MpServer', x=689.50, y=18.00, z=162.50], EntityZombieVillager['Zombie Villager'/4079, l='MpServer', x=685.51, y=19.00, z=157.81]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2739)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-29-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1068078624 bytes (1018 MB) / 2031091712 bytes (1937 MB) up to 3819962368 bytes (3643 MB)
	JVM Flags: 2 total; -Xms1024m -Xmx4098m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version         | Source                                  | Signature                                |
	|:--------- |:---------- |:--------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2          | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp        | 9.42            | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99       | forge-1.12.2-14.23.4.2739-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.4.2739    | forge-1.12.2-14.23.4.2739-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | guideapi   | 1.12-2.1.6-61   | Guide-API-1.12-2.1.6-61.jar             | None                                     |
	| UCHIJAAAA | bloodmagic | 1.12.2-2.3.1-99 | BloodMagic-1.12.2-2.3.1-99.jar          | None                                     |
	| UCHIJAAAA | jei        | 4.11.0.202      | jei_1.12.2-4.11.0.202.jar               | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.48' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
```

**Comment by the-physicser** [comment]
I've run into pretty much the same issue, though it's not necessarily the Burning Furnace pages.

I could add another crash report if that would be helpful, but I also have a fair number of additional mods installed, so it wouldn't be nearly as "clean" as the one already posted.

**Comment by TehNut** [comment]
Fairly sure this is due to a change I made in GuideAPI. I'll take a look later tonight

**Comment by kwill1429** [comment]
Seeing as this version of the mod is used in the latest version of the Direwolf20 pack, I made a small coremod to patch the issue. https://github.com/kwill1429/GuideAPI2.1.6BookFixer

**Comment by TehNut** [comment]
Why not, I don't know... Submit a PR..?

**Comment by kwill1429** [comment]
PR submitted. The patch will remain for users who are a part of a server who won't update until an actual modpack update.

**Comment by TehNut** [comment]
Fixed in newly released gapi build
