### ISSUE TITLE
[1.12.2] Fatal Crash on Teleportion: CAUSES WORLD CORRUPTION!!!!!!

### ISSUE THREAD

**Issue by KittenKoder** [WayofTime/BloodMagic#1407]
#### Issue Description:
Teleportation tile causes fatal multiplayer crash.

#### What happens:
The server crashes when the tile updates. ALSO CAUSES WORLD CORRUPTION!!!!!!

`java.lang.NullPointerException: Ticking block entity
	at WayofTime.bloodmagic.core.data.SoulNetwork.syphonAndDamage(SoulNetwork.java:97)
	at WayofTime.bloodmagic.core.data.SoulNetwork.syphonAndDamage(SoulNetwork.java:119)
	at WayofTime.bloodmagic.tile.TileTeleposer.initiateTeleport(TileTeleposer.java:78)
	at WayofTime.bloodmagic.tile.TileTeleposer.func_73660_a(TileTeleposer.java:54)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)`

#### What you expected to happen:
Not to crash.

#### Steps to reproduce:

1. Teleport with blood network.
2. Repeat.
3. Repeat.
...
?. Crash

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.1-99
- Minecraft: 1.12.2
- Forge: 2705

**Comment by TehNut** [comment]
Should be fixed by #1414
