### ISSUE TITLE
Exception in Fractured Crystal Ritual

### ISSUE THREAD

**Issue by lstanden** [WayofTime/BloodMagic#1530]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
Exception when attempting to run Crack of the Fractured Crystal.  This exception was on the dedicated server console.

[20:33:37] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at WayofTime.bloodmagic.ritual.Ritual.getMaxVolumeForRange(Ritual.java:221) ~[Ritual.class:1.12.2-2.3.3-101]
        at WayofTime.bloodmagic.ritual.Ritual.canBlockRangeBeModified(Ritual.java:203) ~[Ritual.class:1.12.2-2.3.3-101]
        at WayofTime.bloodmagic.ritual.Ritual.setBlockRangeByBounds(Ritual.java:193) ~[Ritual.class:1.12.2-2.3.3-101]
        at WayofTime.bloodmagic.tile.TileMasterRitualStone.setBlockRangeByBounds(TileMasterRitualStone.java:305) ~[TileMasterRitualStone.class:1.12.2-2.3.3-101]
        at WayofTime.bloodmagic.item.ItemRitualReader.func_180614_a(ItemRitualReader.java:146) ~[ItemRitualReader.class:1.12.2-2.3.3-101]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:875) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:492) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

#### What you expected to happen:

Ritual should start breaking crystals and work.

#### Steps to reproduce:

1. Please fractured ritual
2. Start it
3. Observe no crystals being broken
4. Attempt to move ritual
5. Observe error in server console
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 14.23.5.2808

**Comment by keraldi** [comment]
Please post the full crash log via a hosted paste site.

you can use https://gist.github.com/ for that.

What exactly do you mean with "4. Attemt to move ritual"?

**Comment by lstanden** [comment]
Attempt to relocate the ritual using the tinkerer.

There is no crash log -- this doesn't actually crash the game, but the ritual is not breaking crystals (even before attempting to relocate it).  When attempting to relocate it, it shows a message "selected first side", but then throws an exception when you try to select the second side, which is only visible on server console.

**Comment by keraldi** [comment]
First off: The Ritual Tinkerer doesn't work properly yet (fixes have been merged but they're not released yet).

Try the following steps:

1. Set the Ritual Tinkerer to Area Setting mode.
2. Shift-right click the MRS of an activated ritual
3. Select a region within the boundaries set by the ritual (for `RitualCrystalHarvest` (that's the Ritual of the Fractured Crystal) the area can be a maximum of 7x5x7 (that means it cannot exceed 7 blocks in horzontal range and cannot exceed 5 blocks in vertical range).

It will probably modify all Rituals of the Fractured Crystal to have that offset and might carry over saves if you're playing in SSP.

If that doesn't work for you, please wait for the next release. It will have fixes for the Ritual Tinkerer in place that makes using it easier and prevents exceptions.
