### ISSUE TITLE
NPE crash in net.minecraftforge.event.world.WorldEvent$Unload

### ISSUE THREAD

**Issue by LemADEC** [WayofTime/BloodMagic#1598]
#### Issue Description:
Game crashed when unloading TheEnd while running a profiling from JustEnoughRessources.
```
[14:33:13] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save New World
[14:33:13] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Unload@5767310c:
java.lang.NullPointerException: null
	at WayofTime.bloodmagic.util.handler.event.GenericHandler.onWorldUnload(GenericHandler.java:475) ~[GenericHandler.class:1.12.2-2.4.0-102]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_391_GenericHandler_onWorldUnload_Unload.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

#### What happens:
Game crashed to launcher.

#### What you expected to happen:
No crash

#### Steps to reproduce:
Issue is intermittent, was only seen once so far:
1. create new world
2. type /jer_profile 1000 all
3. wait for profile to finish
=> no crash expected

#### Affected Versions (Do *not* use "latest"):
- BloodMagic: 1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- JustEnoughResources: 1.12.2-0.9.0.53

**Comment by keraldi** [comment]
Please provide a full crashlog.

**Comment by keraldi** [comment]
https://github.com/WayofTime/BloodMagic/commit/f997aee8917176d39d92bd80aea1ff6cbcc452fb

**Comment by LemADEC** [comment]
I had a couple other occurrences, it seems related to fast load/unloading the end dimension, typically while reusing an existing world instead of creating a new one.
