### ISSUE TITLE
[1.16.4] Living armor crash

### ISSUE THREAD

**Issue by UnfortunateName** [WayofTime/BloodMagic#1718]
Crash from putting on living armor after enchanting with Apotheosis. In a new world I wasn't able to recreate it after a few attempts quickly (it's 7am and I haven't slept so only did a quick test). Here's from my level.dat showing what enchants were on them, and I equipped them from boots up and crashed when I got the full set on. The helmet just has normal Minecraft enchants so I'm guessing that it wasn't specific to the helmet but something to do with the full set being equipped with one of these enchants on a piece? 

I haven't used the mod before and have no idea how the living armor works as I was just getting it made to test it, so I can't think of what else might have caused it.

From the level.dat (sorry for formatting, didn't know proper way to view it so just used a basic text reader):
Slotdidbloodmagic:livingbootsCount
tagDamage	Enchantments
lvlidminecraft:depth_striderlvlidnaturesaura:aura_mendinglvlidminecraft:fire_protectionlvlidapotheosis:berserklvlidminecraft:blast_protectionSloteidbloodmagic:livingleggingsCount
tagDamage	Enchantments
lvlidminecraft:blast_protectionlvlidtombstone:soulboundlvlidminecraft:unbreakinglvlidminecraft:feather_fallingSlotfidbloodmagic:livingplateCount
tagDamage	Enchantments
lvlidminecraft:fire_protectionlvlidminecraft:blast_protectionlvlidapotheosis:life_mendinglvlidapotheosis:berserklvlidapotheosis:icy_thornsSlotgidbloodmagic:livinghelmetCount
tagDamage	Enchantments
lvlidminecraft:blast_protectionlvlidminecraft:respirationlvlidminecraft:aqua_affinitylvlidminecraft:fire_protection

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.0.2-7
- Minecraft: 1.16.4
- Forge: 35.1.10

**Comment by TehNut** [comment]
We need a copy of the crash report itself

**Comment by UnfortunateName** [comment]
Sorry about that! Had it in pastebin and the link in my clipboard and just forgot to add it. It didn't generate an actual crashlog, so here's the end of the latest as the full one was too long to add. After I get some sleep and get back on my computer I can find more if this isn't enough. 
https://pastebin.com/yGh0LLdF

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/util/handler/event/GenericHandler.java#L406

I'm not sure how that's null... I assume it's a fully fresh set? I wouldn't be surprised if there's a race condition.

**Comment by UnfortunateName** [comment]
Yup fully fresh. Created less than 5 minutes before, and enchanted within the last minute before the crash, never worn until the very end.

**Comment by MisterFister69** [comment]
I also encounter this using **BloodMagic-1.16.3-3.0.2-7**
It appears that it has to do with first time using the living armor set.
Here are the things I tested so far and what crashed and what not:

- In creative, I took full living armor set from creative menu and equip all. **NO CRASH**
- Next, I tried making the living armor set, with the enchants I have before. **CRASHED AFTER TRYING TO WEAR THE LAST PIECE**
- Then, I tried making the living armor set, **without** enchants. **STILL CRASH AFTER TRYING TO WEAR THE LAST PIECE**
- The last test was interesting. I tried making the living armor set again. but this time I didn't make them all. Instead, I tried to take out a living chest piece from the creative menu and equip all. ""NO CRASH""

Here's a crash report:

> ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/10/20 8:25 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at wayoftime.bloodmagic.util.handler.event.GenericHandler.onEntityUpdate(GenericHandler.java:406) ~[bloodmagic:1.16.3-3.0.2-7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_419_GenericHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[forge:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:randompatches:RandomPatches PlayerEntity Transformer,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227) ~[?:?] {re:classloading,xf:fml:lightoverlay-forge:light-overlay-forge}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at wayoftime.bloodmagic.util.handler.event.GenericHandler.onEntityUpdate(GenericHandler.java:406) ~[bloodmagic:1.16.3-3.0.2-7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_419_GenericHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[forge:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:randompatches:RandomPatches PlayerEntity Transformer,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 36
	Entity Name: (I'm hiding this)
	Entity's Exact location: 81.71, 4.00, 218.77
	Entity's Block location: World: (81,4,218), Chunk: (at 1,0,10 in 5,13; contains blocks 80,0,208 to 95,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:400) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:227) ~[?:?] {re:classloading,xf:fml:lightoverlay-forge:light-overlay-forge}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

**Comment by Rue82** [comment]
I also encountered this bug while playing on a server.  Every time I try to log in I get an Internal Server Error message.  Brand new set, crashed after equipping the last piece like the others here.  BloodMagic-1.16.3-3.0.2-7.  Hopefully that information can help.

**Comment by TehNut** [comment]
I've already informed Way of the issue, but he's busy until Tuesday. I would suggest grabbing the chestplate from the creative menu instead of crafting it if you wish to use it.

```
TehNut 12/09/2020
@WayofTime https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/util/handler/event/GenericHandler.java#L342-L344

This should be changed to

stats = getStats(...)
if (stats != null) ...

fromPlayer checks full set already and unless you pass true to the overload, the method is still nullable
If the chest plate doesn't have stats, but they're wearing a full set, the poison level call will error
Or any other calls before that if they apply, that's just the only one outside an if

WayofTime 12/09/2020
Ah ok, because I assume enchants add an NBT tag to the item, but the training hasn't started, so to speak

TehNut 12/09/2020
Probably
Depends on when livingstats is getting created after crafting it
Creative chests are ok because they have the default data

WayofTime 12/09/2020
That'd explain that
```

**Comment by WayofTime** [comment]
Fixed
