### ISSUE TITLE
Client Crashes when equipping the last piece of living armor 

### ISSUE THREAD

**Issue by Flo9400** [WayofTime/BloodMagic#1743]
#### Issue Description:
The client crashes when equipping the last piece of the living armor equipment. 
Client side error message: "Internal Exception: java.IOException: An existing connection was forcibly closed by the remote host."
Server error log:
"caused by: java.lang.NullPointerException
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null"

Another individual has the same problem, as stated in this reddit post: 
https://www.reddit.com/r/direwolf20/comments/kkub3y/psa_possible_blood_magic_crash/

#### What happens:
When equipping the last piece of living armor the client crashes and is no longer able to join the server without altering his player file. 

#### What you expected to happen:
To equip the piece of armor and to properly function as intended. 

#### Steps to reproduce:

1. Equip the last piece of the living armor set.
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.3-3.0.3-8  & BloodMagic-1.16.3-3.0.2-7
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by WayofTime** [comment]
Please post the full log here.

**Comment by WayofTime** [comment]
And I assume both client and server have the latest version of BM installed? I fixed a similar crash in 3.0.2-7.

**Comment by raccont** [comment]
Edit: This entire comment is based on the fact that I thought I was running the latest version. My version WAS in fact 3.0.2-7 and the crash did indeed not happend again after upgrading to 3.0.3-8.


--------

Happened to me as well, running in version BloodMagic-1.16.3-3.0.2-7. I was not sprinting, food level was below 19, I was standing still, I was not on fire, not poisoned, wearing no shield and nothing else except for the armor. Here's the full output log:
```
[05/01/2021 11:28:27 AM] [11:28:27] [Server thread/ERROR]: Exception caught during firing event: null
[05/01/2021 11:28:27 AM] 	Index: 2
[05/01/2021 11:28:27 AM] 	Listeners:
[05/01/2021 11:28:27 AM] 		0: HIGHEST
[05/01/2021 11:28:27 AM] 		1: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@67fd8c66
[05/01/2021 11:28:27 AM] 		2: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@3d03406c onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		3: NORMAL
[05/01/2021 11:28:27 AM] 		4: ASM: com.legacy.leap.LeapEntityEvents@4cc5b889 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		5: ASM: class corgitaco.betterweather.BetterWeather$BetterWeatherEvents entityTickEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		6: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@7a49b55a
[05/01/2021 11:28:27 AM] 		7: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@16b97311
[05/01/2021 11:28:27 AM] 		8: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@78c78ca3
[05/01/2021 11:28:27 AM] 		9: ASM: com.legacy.scuba_gear.ScubaEvents@9769edf onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		10: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@3d03406c onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		11: ASM: class cofh.ensorcellation.event.ShieldEnchEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		12: ASM: class cofh.ensorcellation.event.HorseEnchEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		13: ASM: class cofh.ensorcellation.event.CommonEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		14: ASM: class vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		15: ASM: wile.engineersdecor.ModEngineersDecor@36faa318 onPlayerEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		16: ASM: class com.stal111.forbidden_arcanus.event.PlayerTickListener onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		17: ASM: com.legacy.step.StepEntityEvents@763e872 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		18: ASM: class com.teammetallurgy.aquaculture.item.neptunium.NeptuniumArmor onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		19: ASM: class com.simibubi.create.events.CommonEvents onUpdateLivingEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		20: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem holdingExtendoGripIncreasesRange(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		21: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@7352a161
[05/01/2021 11:28:27 AM] 		22: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@44062934
[05/01/2021 11:28:27 AM] 		23: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@19faeb5e
[05/01/2021 11:28:27 AM] 		24: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@5d1cde56
[05/01/2021 11:28:27 AM] 		25: ASM: tschipp.carryon.common.event.ItemEvents@410d9d31 dropNonHotbarItems(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		26: ASM: tschipp.carryon.common.event.ItemEntityEvents@17a08387 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		27: net.minecraftforge.eventbus.EventBus$$Lambda$2906/668225854@3ba3253d
[05/01/2021 11:28:27 AM] 		28: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@3893939d tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		29: ASM: mekanism.common.lib.radiation.RadiationManager@759d480c onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		30: ASM: flaxbeard.immersivepetroleum.common.CommonEventHandler@386579f7 test(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		31: ASM: blusunrize.immersiveengineering.common.EventHandler@75d06329 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		32: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@2db8ecdf onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		33: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@50ef7eb onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		34: ASM: vazkii.quark.content.world.module.BiotiteModule@4f79416 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] 		35: ASM: squeek.appleskin.network.SyncHandler@45f93627 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[05/01/2021 11:28:27 AM] java.lang.NullPointerException
[05/01/2021 11:28:27 AM] 	at wayoftime.bloodmagic.util.handler.event.GenericHandler.onEntityUpdate(GenericHandler.java:406)
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.eventbus.ASMEventHandler_534_GenericHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:315)
[05/01/2021 11:28:27 AM] 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112)
[05/01/2021 11:28:27 AM] 	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)
[05/01/2021 11:28:27 AM] 	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
[05/01/2021 11:28:27 AM] 	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
[05/01/2021 11:28:27 AM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
[05/01/2021 11:28:27 AM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
[05/01/2021 11:28:27 AM] 	at java.lang.Thread.run(Thread.java:748)
[05/01/2021 11:28:27 AM] 
[05/01/2021 11:28:27 AM] [11:28:27] [Server thread/FATAL]: Preparing crash report with UUID 410fd6cb-d756-4fab-9dd0-10f9ec9be890
[05/01/2021 11:28:27 AM] [Server thread/ERROR]: Encountered an unexpected exception
[05/01/2021 11:28:27 AM] net.minecraft.crash.ReportedException: Ticking player
[05/01/2021 11:28:27 AM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
[05/01/2021 11:28:27 AM] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[05/01/2021 11:28:27 AM] Caused by: java.lang.NullPointerException
[05/01/2021 11:28:27 AM] 	at wayoftime.bloodmagic.util.handler.event.GenericHandler.onEntityUpdate(GenericHandler.java:406) ~[bloodmagic:1.16.3-3.0.2-7]
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.eventbus.ASMEventHandler_534_GenericHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
[05/01/2021 11:28:27 AM] 	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:315) ~[forge:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
[05/01/2021 11:28:27 AM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
[05/01/2021 11:28:27 AM] 	... 6 more
[05/01/2021 11:28:27 AM] 2021-01-05 11:28:27,812 Thread-5 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
[05/01/2021 11:28:39 AM] AL lib: (EE) alc_cleanup: 1 device not closed
[05/01/2021 11:28:39 AM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
```

**Comment by WayofTime** [comment]
Yeah, the above crash was because of some mis-assumptions I had with the rewritten Living Armour, which I have since fixed. 

If there aren't any crashes on the latest version, I'll close this tomorrow.
