### ISSUE TITLE
Client Crashes

### ISSUE THREAD

**Issue by GoodOldeTymes** [WayofTime/BloodMagic#1750]
#### Issue Description:
Client and server crashes a few seconds after logging into multiplayer.

#### What happens:
Both the client and the server have the same version of the mod installed.  After a few seconds of being in the server, both the client and the server crashes.  I get this error report:

Time: 1/15/21 7:56 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at wayoftime.bloodmagic.tile.TileAltar.invalidateCaps(TileAltar.java:229) ~[?:1.16.3-3.0.4-9] {re:classloading}
	at net.minecraft.tileentity.TileEntity.onChunkUnloaded(TileEntity.java:149) ~[?:?] {re:classloading}
	at net.minecraft.world.World.lambda$tickBlockEntities$4(World.java:472) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World$$Lambda$6184/1640746887.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476) ~[?:1.8.0_51] {}
	at net.minecraft.world.World.func_217391_K(World.java:472) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:226) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$439/654740048.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at wayoftime.bloodmagic.tile.TileAltar.invalidateCaps(TileAltar.java:229) ~[?:1.16.3-3.0.4-9] {re:classloading}
	at net.minecraft.tileentity.TileEntity.onChunkUnloaded(TileEntity.java:149) ~[?:?] {re:classloading}
	at net.minecraft.world.World.lambda$tickBlockEntities$4(World.java:472) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World$$Lambda$6184/1640746887.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476) ~[?:1.8.0_51] {}
	at net.minecraft.world.World.func_217391_K(World.java:472) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:226) ~[?:?] {re:classloading,xf:OptiFine:default}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['GoodOldTymes'/168, l='ClientLevel', x=-174.77, y=64.00, z=-1001.49]]
	Chunk stats: Client Chunk Cache: 729, 484
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,64,-160), Chunk: (at 0,4,0 in 14,-10; contains blocks 224,0,-160 to 239,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 46604908 game time, 48926961 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$439/654740048.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1050024552 bytes (1001 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		tombstone-1.16-6.2.0.jar                          |Corail Tombstone              |tombstone                     |1.16-6.2.0          |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		reliquary-1.16.3-1.3.4.1061.jar                   |Reliquary                     |xreliquary                    |1.16.3-1.3.4.1061   |DONE      |NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |DONE      |NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
		environmentalcreepers-forge-1.16.3-1.6.0.jar      |Environmental Creepers        |environmentalcreepers         |1.6.0               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE
		cloth-config-forge-4.1.1.jar                      |Cloth Config v4 API           |cloth-config                  |4.0                 |DONE      |NOSIGNATURE
		VillagersRespawn-1.16.4-1.16.4-1.35.0.3.jar       |Villagers Respawn  Mod        |villagersrespawn              |1.16.4-1.35.0.3     |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.3-3.0.4-9.jar                     |Blood Magic                   |bloodmagic                    |1.16.3-3.0.4-9      |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		light-overlay-5.5.4.jar                           |Light Overlay Forge           |lightoverlay-forge            |NONE                |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.0.2.jar                 |Comforts                      |comforts                      |1.16.4-4.0.0.2      |DONE      |NOSIGNATURE
	Crash Report UUID: 1b75eaee-de4f-47d0-a9c5-72e1c212fb04
	Launched Version: 1.16.4-forge-35.1.13
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor 
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

#### What you expected to happen:
To be able to play.

#### Steps to reproduce:

1. Install Blood Magic on server and client
2. Login to server
3. Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.0.4-9
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by WayofTime** [comment]
Update Blood Magic~
