### ISSUE TITLE
Compatability issue with Eidolon

### ISSUE THREAD

**Issue by Wubadubb** [WayofTime/BloodMagic#1802]
#### Issue Description:
When I use these two mods together the game crashes. Both work on their own, just not together.

#### What happens:
Game opens, if it doesn't crash on opening world, does three seconds in.

#### What you expected to happen:
Not immediatly crashing.

#### Steps to reproduce:

1. Have 1.16.4 Eidolon & Blood magic with needed libraries
2. Open World
3. You will either crash on 100% loaded or when you see the world
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: All 1.16.4 versions
- Minecraft: 1.16.4
- Forge: Forge 1.16.4 35.1.4

**Comment by wrincewind** [comment]
Do you have a crashlog we can look at?

You can upload it to a service like pastebin, for preference.

**Comment by Wubadubb** [comment]
> Do you have a crashlog we can look at?

Yes, though I have to ctrl v from logs because it wont let me view them.
The mods I am using are Eidolon, Blood Magic, JEI, and Curious (required by Eidolon)
11:40:00.630
at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:634) ~[?:?] {re:classloading}
11:40:00.630
at net.minecraft.block.Block.func_220070_a(Block.java:228) ~[?:?] {re:classloading,pl:accesstransformer:B}
11:40:00.630
at net.minecraft.block.Block.func_220059_a(Block.java:248) ~[?:?] {re:classloading,pl:accesstransformer:B}
11:40:00.630
at net.minecraft.fluid.WaterFluid.func_205580_a(WaterFluid.java:64) ~[?:?] {re:classloading}
11:40:00.630
at net.minecraft.fluid.FlowingFluid.func_205574_a(FlowingFluid.java:241) ~[?:?] {re:classloading}
11:40:00.630
at net.minecraft.fluid.FlowingFluid.func_207937_a(FlowingFluid.java:146) ~[?:?] {re:classloading}
11:40:00.630
at net.minecraft.fluid.FlowingFluid.func_205575_a(FlowingFluid.java:125) ~[?:?] {re:classloading}
11:40:00.630
at net.minecraft.fluid.FlowingFluid.func_207191_a(FlowingFluid.java:410) ~[?:?] {re:classloading}
11:40:00.631
at net.minecraft.fluid.FluidState.func_206880_a(FluidState.java:70) ~[?:?] {re:classloading}
11:40:00.631
at net.minecraft.world.server.ServerWorld.func_205339_a(ServerWorld.java:583) ~[?:?] {re:classloading}
11:40:00.631
at net.minecraft.world.server.ServerWorld$$Lambda$5984/53832816.accept(Unknown Source) ~[?:?] {}
11:40:00.631
at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84) ~[?:?] {re:classloading}
11:40:00.631
at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:337) ~[?:?] {re:classloading}
11:40:00.631
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
11:40:00.631
... 6 more
11:40:04.795
AL lib: (EE) alc_cleanup: 1 device not closed
11:40:05.813
Process crashed with exit code -1

**Comment by Wubadubb** [comment]
> Do you have a crashlog we can look at?
> 
> You can upload it to a service like pastebin, for preference.

https://pastebin.com/RsJCrs3W
Sorry, internet was out for a while.

**Comment by wrincewind** [comment]
Closing as 1.16 is out-of-support.
