### ISSUE TITLE
teleposer ticking

### ISSUE THREAD

**Issue by marineboone** [WayofTime/BloodMagic#1905]
#### Issue Description:
when using teleposer get ticking block error

#### Steps to reproduce:

1. place teleposers
2. place the blocks u want to move on top(empty teleposer
3. use lever
4. get ticking block error
[crash-2022-04-13_20.09.01-client.txt](https://github.com/WayofTime/BloodMagic/files/9060066/crash-2022-04-13_20.09.01-client.txt)

...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 1.18.2
- Forge:

**Comment by Kokice5** [comment]
this is the worst template reading i ever saw

**Comment by dphaldes** [comment]
> java.lang.NullPointerException: mouseClicked event handler
	at dev.ftb.mods.ftbchunks.client.map.MapDimension.getCurrent(MapDimension.java:41) ~[?:1605.3.2-build.115] {re:classloading}
	at dev.ftb.mods.ftbchunks.client.LargeMapScreen.<init>(LargeMapScreen.java:65) ~[?:1605.3.2-build.115] {re:classloading}
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient.openGui(FTBChunksClient.java:217) ~[?:1605.3.2-build.115] {re:classloading,re:mixin}
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient.customClick(FTBChunksClient.java:403) ~[?:1605.3.2-build.115] {re:classloading,re:mixin}
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient$$Lambda$8360/1606725881.act(Unknown Source) ~[?:?] {}
	
Looks like ftbchunks issue to me

**Comment by wrincewind** [comment]
closing as 1.16 is no longer supported.
