### ISSUE TITLE
[1.18.2] Cannot Catch Fish While Mod is Installed

### ISSUE THREAD

**Issue by PhiliaHalls** [WayofTime/BloodMagic#1918]
#### Issue Description:
With the most recent build as of 8/8/2022, you cannot fish while Blood Magic is installed.

#### What happens:
When you try to reel in a catch, you cannot reel in anything that bites your line.

#### What you expected to happen:
I expected to be able to reel in what bit the fishing line

#### Steps to reproduce:

1. Get a fishing rod
2. Cast a line into a fishable body of water
3. Wait for something to bite
4. When you get a bite, try to reel in the catch
5. You're unable to reel in the line until the bite is gone

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.18.2-3.2.4-39
- Minecraft: 1.18.2
- Forge: 40.1.68

I have tested this in an instance with only Blood Magic and Patchouli, and an instance with only Patchouli.

**Comment by baranelitez** [comment]
I do confirm this. here's the error my server produces when this happens:

```
[02:39:25] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@5c7db7e5, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.storage.loot.LootContext.m_78953_(net.minecraft.world.level.storage.loot.parameters.LootContextParam)" is null
	at wayoftime.bloodmagic.loot.GlobalLootModifier$VoidingModifier.doApply(GlobalLootModifier.java:319) ~[BloodMagic-1.18.2-3.2.4-39.jar%2353!/:1.18.2-3.2.4-39] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge-1.18.2-40.1.68-universal.jar%23130!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1244) ~[forge-1.18.2-40.1.68-universal.jar%23130!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:89) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,re:classloading,pl:mixin:APP:botania_xplat.mixins.json:MixinLootTable,pl:mixin:APP:quark.mixins.json:accessor.AccessorLootTable,pl:mixin:A}
	at net.minecraft.world.entity.projectile.FishingHook.m_37156_(FishingHook.java:415) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothlure}
	at net.minecraft.world.item.FishingRodItem.m_7203_(FishingRodItem.java:24) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:252) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:291) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1015) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:25) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

**Comment by WayofTime** [comment]
I'll release a minor patch tomorrow with the fix for this.

**Comment by WayofTime** [comment]
This is now fixed in the latest release, once CurseForge finishes processing.

**Comment by DasBrain** [comment]
Probably related - I got a crash when running the Marine Fisher from Industrial Foregoing.

<pre>
Time: 8/10/22, 6:17 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.storage.loot.LootContext.m_78953_(net.minecraft.world.level.storage.loot.parameters.LootContextParam)" is null
	at wayoftime.bloodmagic.loot.GlobalLootModifier$VoidingModifier.doApply(GlobalLootModifier.java:319) ~[BloodMagic-1.18.2-3.2.4-39.jar%2380!/:1.18.2-3.2.4-39] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge-1.18.2-40.1.68-universal.jar%23357!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1244) ~[forge-1.18.2-40.1.68-universal.jar%23357!/:?] {re:mixin,re:classloading,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:89) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at com.buuz135.industrial.block.resourceproduction.tile.MarineFisherTile.work(MarineFisherTile.java:79) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialWorkingTile.lambda$new$0(IndustrialWorkingTile.java:91) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.hrznstudio.titanium.component.progress.ProgressBarComponent.tickBar(ProgressBarComponent.java:189) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:43) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:238) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialAreaWorkingTile.serverTick(IndustrialAreaWorkingTile.java:134) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialAreaWorkingTile.serverTick(IndustrialAreaWorkingTile.java:55) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$3(BasicTileBlock.java:80) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:beyond_earth.mixin.json:BlockSet,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:simplerpc.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

&lt;snip&gt;
</pre>

**Comment by WayofTime** [comment]
Probably - see if this happens on the latest version. If it does I'll continue my investigations.

**Comment by DasBrain** [comment]
Thanks, updating Blood Magic fixed this.
(This was just for your information - that issue can crash the world.)
