### ISSUE TITLE
Mark of the Falling Tower

### ISSUE THREAD

**Issue by NekoSpirits** [WayofTime/BloodMagic#1923]
#### Issue Description:
Trying to use the mark of the Falling tower in a custom modpack, wouldn't work. Made a new profile with just Blood Magic, still does not work.

#### What happens:
Ritual activates, does not consume the block of diamond,

#### What you expected to happen:
The block of diamond to be consumed, and a meteor to be summoned from the sky

#### Steps to reproduce:

1. Use Ritual Diviner to assemble the Mark of the Falling Tower.
2. Have 250,000 LP in your network, or use a creative activation crystal on the master ritual stone
3. Throw catalyst (Tried Iron block, Diamond Block, Gold Block)
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4-3.1.13-39
- Minecraft: 1.16.5
- Forge: 36.2.39
![javaw_tet6qNusik](https://user-images.githubusercontent.com/20034469/186920815-f524943d-0720-49ae-a2fb-55fee6a663d5.gif)
![javaw_PAGaR8ifyo](https://user-images.githubusercontent.com/20034469/186920939-d68c8e20-409c-497e-8b50-978c44c1088c.gif)
(gifs split due to size limitations)

**Comment by WayofTime** [comment]
The guide should say that it requires an additional amount of LP in your Soul Network. Also, it is a diamond, not a diamond block.
https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/resources/data/bloodmagic/patchouli_books/guide/en_us/entries/rituals/ritual_list/ritual_meteor.json

**Comment by NekoSpirits** [comment]
Okay, I did not see that anywhere in the Sanguine Scientiem, looked back through it this time and saw this error, there are no references in the "latest.log", is this logged somewhere different?
![javaw_9KREtNuocJ](https://user-images.githubusercontent.com/20034469/186932665-83d8162a-164b-4ece-9706-6fa706463457.png)


Edit: Found it

`[10:48:23] [main/ERROR]: Error while loading contents for book bloodmagic:guide
java.lang.RuntimeException: Error building entry bloodmagic:rituals/ritual_list/ritual_meteor
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[?:1.16.4-53.3]
	at vazkii.patchouli.client.book.BookContents$$Lambda$30162/1361860299.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$Values.forEach(HashMap.java:972) ~[?:1.8.0_51]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) [?:1.16.4-53.3]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) [?:1.16.4-53.3]
	at vazkii.patchouli.common.book.BookRegistry$$Lambda$30151/434609011.accept(Unknown Source) [?:1.16.4-53.3]
	at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_51]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:105) [?:1.16.4-53.3]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) [?:1.16.4-53.3]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) [?:1.16.4-53.3]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.handler$bhm000$patchouli_onSync(SourceFile:518) [?:?]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1276) [?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) [?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$28931/1094106668.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:179) [?:0.12.1.128]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:52) [?:0.12.1.128]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:36) [?:0.12.1.128]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) [?:0.12.1.128]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) [?:0.12.1.128]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) [?:0.12.1.128]
	at mezz.jei.load.PluginLoader.lambda$new$3(PluginLoader.java:109) [?:7.7.1.152]
	at mezz.jei.load.PluginLoader$$Lambda$29863/1398375934.accept(Unknown Source) [?:7.7.1.152]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) [?:7.7.1.152]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:109) [?:7.7.1.152]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$27603/243273823.accept(Unknown Source) [?:7.7.1.152]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3015/793068998.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3220/1546957042.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes.lambda$handle$2(FMLPlayMessages.java:412) [?:?]
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes$$Lambda$29691/620755401.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:201) [?:?]
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes.handle(FMLPlayMessages.java:391) [?:?]
	at net.minecraftforge.fml.network.NetworkInitialization$$Lambda$3072/553229336.accept(Unknown Source) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$28333/507811033.accept(Unknown Source) [?:?]
	at java.util.Optional.ifPresent(Optional.java:159) [?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$3013/1660409789.accept(Unknown Source) [?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3015/793068998.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3220/1546957042.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$28321/1296073134.apply(Unknown Source) [?:?]
	at java.util.Optional.map(Optional.java:215) [?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1905) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$28931/1094106668.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$501/1448780972.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry bloodmagic:rituals/ritual_list/ritual_meteor page 3
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[?:1.16.4-53.3]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-53.3]`

**Comment by Hybrid-Soul** [comment]
How do you fix the data entries loading wrong?  I have a few that loaded either wrong or not at all that I would like to use.
