### ISSUE TITLE
Error on starting server ([minecraft:root / minecraft:worldgen/biome]: [bloodmagic:none])

### ISSUE THREAD

**Issue by Gustavo-Salvador** [WayofTime/BloodMagic#1946]
#### Issue Description:
I am playing at a server with the stoneblock 3 modpack installed, the server was running normally, but one day for some reason when i started the server it crashed.

#### the crash report:
[16:43:36] [ServerMain/ERROR]: Exception reading ./world/level.dat
java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/noise_settings / bloodmagic:none]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/noise_settings] (Stable)]
        at gs$c.a(SourceFile:159) ~[server-1.18.2.jar:?]
        at ctz.<init>(SourceFile:86) ~[server-1.18.2.jar:?]
        at ctz.<init>(SourceFile:76) ~[server-1.18.2.jar:?]
        at com.mojang.datafixers.util.Function5.lambda$null$2(Function5.java:14) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult$Instance.ap3(DataResult.java:337) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:321) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:249) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.BaseMapCodec.lambda$decode$2(BaseMapCodec.java:31) ~[datafixerupper-4.1.27.jar:?]
        at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667) ~[?:?]
        at com.mojang.serialization.codecs.BaseMapCodec.decode(BaseMapCodec.java:27) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.UnboundedMapCodec.lambda$decode$0(UnboundedMapCodec.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.UnboundedMapCodec.decode(UnboundedMapCodec.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.1.27.jar:?]
        at hd$1.decode(SourceFile:65) ~[server-1.18.2.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:324) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder$1.decode(Decoder.java:49) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.decode(Decoder.java:22) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:26) ~[datafixerupper-4.1.27.jar:?]
        at dkp.a(SourceFile:119) ~[server-1.18.2.jar:?]
        at dkp.a(SourceFile:229) ~[server-1.18.2.jar:?]
        at dkp.a(SourceFile:191) ~[server-1.18.2.jar:?]
        at dkp$a.a(SourceFile:351) ~[server-1.18.2.jar:?]
        at net.minecraft.server.Main.a(SourceFile:164) ~[server-1.18.2.jar:?]
        at zk.a(SourceFile:40) ~[server-1.18.2.jar:?]
        at net.minecraft.server.Main.main(SourceFile:155) ~[server-1.18.2.jar:?]
        at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[16:43:36] [ServerMain/ERROR]: Exception reading ./world/level.dat_old
java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/noise_settings / bloodmagic:none]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/noise_settings] (Stable)]
        at gs$c.a(SourceFile:159) ~[server-1.18.2.jar:?]
        at ctz.<init>(SourceFile:86) ~[server-1.18.2.jar:?]
        at ctz.<init>(SourceFile:76) ~[server-1.18.2.jar:?]
        at com.mojang.datafixers.util.Function5.lambda$null$2(Function5.java:14) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult$Instance.ap3(DataResult.java:337) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:321) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:249) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.BaseMapCodec.lambda$decode$2(BaseMapCodec.java:31) ~[datafixerupper-4.1.27.jar:?]
        at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667) ~[?:?]
        at com.mojang.serialization.codecs.BaseMapCodec.decode(BaseMapCodec.java:27) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.UnboundedMapCodec.lambda$decode$0(UnboundedMapCodec.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.UnboundedMapCodec.decode(UnboundedMapCodec.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.1.27.jar:?]
        at hd$1.decode(SourceFile:65) ~[server-1.18.2.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:324) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder$1.decode(Decoder.java:49) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.decode(Decoder.java:22) ~[datafixerupper-4.1.27.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:26) ~[datafixerupper-4.1.27.jar:?]
        at dkp.a(SourceFile:119) ~[server-1.18.2.jar:?]
        at dkp.a(SourceFile:229) ~[server-1.18.2.jar:?]
        at dkp.a(SourceFile:199) ~[server-1.18.2.jar:?]
        at dkp$a.a(SourceFile:351) ~[server-1.18.2.jar:?]
        at net.minecraft.server.Main.a(SourceFile:164) ~[server-1.18.2.jar:?]
        at zk.a(SourceFile:40) ~[server-1.18.2.jar:?]
        at net.minecraft.server.Main.main(SourceFile:155) ~[server-1.18.2.jar:?]
        at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[16:43:37] [ServerMain/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [bloodmagic:none]
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(SourceFile:194) ~[server-1.18.2.jar:?]
        at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [bloodmagic:none]
        at gw.j(SourceFile:325) ~[server-1.18.2.jar:?]
        at hc$d.c(SourceFile:121) ~[server-1.18.2.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at hc$b.<init>(SourceFile:161) ~[server-1.18.2.jar:?]
        at hc.f(SourceFile:322) ~[server-1.18.2.jar:?]
        at net.minecraft.server.Main.a(SourceFile:190) ~[server-1.18.2.jar:?]
        at zk.a(SourceFile:40) ~[server-1.18.2.jar:?]
        at net.minecraft.server.Main.main(SourceFile:155) ~[server-1.18.2.jar:?]
        ... 2 more
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.18.2-3.2.6-41
- Minecraft: 1.18.2
- Forge: 40.1.80
- Stoneblock 3: 1.4.3

**Comment by wrincewind** [comment]
Closing as 1.18 is out of support.
