### ISSUE TITLE
how to downgrade living armor

### ISSUE THREAD

**Issue by silvaro44** [WayofTime/BloodMagic#1951]
#### Issue Description:
Note: idk if its a bug watched like 100 vids but still dont know how to downgrade my armor

#### Steps to reproduce:

1. build ritual
2. activate
3. try
...be disapointed

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.5
- Minecraft: 1.16.5
- Forge: 1.16.5

**Comment by eldediamante** [comment]
I have the same problem, no solution yet?

I think this is the error I'm getting:
- 14.02 21:36:19 [Server] Startup[20:36:19 [ERROR]]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@697c987, suppressing error
14.02 21:36:19 [Server] [INFO] java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
14.02 21:36:19 [Server] [INFO] at wayoftime.bloodmagic.ritual.Ritual.getMaxHorizontalRadiusForRange(Ritual.java:256) ~[BloodMagic-1.18.2-3.2.6-41.jar%2382!/:1.18.2-3.2.6-41]
14.02 21:36:19 [Server] [INFO] at wayoftime.bloodmagic.common.item.ItemRitualReader.m_6225_(ItemRitualReader.java:215) ~[BloodMagic-1.18.2-3.2.6-41.jar%2382!/:1.18.2-3.2.6-41]
14.02 21:36:19 [Server] [INFO] at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooksMixin.java:628) ~[forge-1.18.2-40.2.14-universal.jar%23223!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.world.item.ItemStack.m_41661_(ItemStackMixin.java:222) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameModeMixin.java:861) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerPlayNetHandlerMixin.java:985) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.md73bb18$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23218!/:?]
14.02 21:36:19 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by wrincewind** [comment]
just checking, but are you sure the chest is in the right place, as indicated in the 3D render in the manual? Are you wearing a training bracelet?

**Comment by eldediamante** [comment]
The chest is set correctly, and I have now tried with the bracelet, and it still does not work.

**Comment by eldediamante** [comment]
![imagen_2024-02-14_231648260](https://github.com/WayofTime/BloodMagic/assets/55103304/138d0a1f-7a8a-4a05-965a-ba67d77373b9)

**Comment by wrincewind** [comment]
Are you wearing the full set of living armour when you activate the ritual?

**Comment by eldediamante** [comment]
By the way, I'm on a server (maybe that helps?). Yes, I do have the entire set of armor equipped.

**Comment by eldediamante** [comment]
Any updates? or do you need more information?

**Comment by wrincewind** [comment]
sadly, 1.16 is no longer supported, so we're going to have to close this issue.
