### ISSUE TITLE
[1.20.1 Alpha] Dedicated server crash on load

### ISSUE THREAD

**Issue by gardenappl** [WayofTime/BloodMagic#1971]
#### Issue Description:
Modded dedicated 1.20.1 server with Blood Magic crashes due to:
```
        Caused by 1: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/EntityRendererProvider$Context
                at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
                at java.lang.Class.privateGetDeclaredConstructors(Class.java:3473) ~[?:?] {re:mixin}
                at java.lang.Class.getConstructor0(Class.java:3678) ~[?:?] {re:mixin}
                at java.lang.Class.getConstructor(Class.java:2368) ~[?:?] {re:mixin}
                at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:75) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.lambda$getListenerListInternal$0(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:61) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.LockHelper.get(LockHelper.java:44) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:39) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:50) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:276) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:244) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:199) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:193) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:187) ~[eventbus-6.0.5.jar%2352!/:?] {}
                at wayoftime.bloodmagic.BloodMagic.<init>(BloodMagic.java:124) ~[bloodmagic-1.20.1-3.3.0-42.jar%23422!/:1.20.1-3.3.0-42] {re:classloading}
                at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.3.jar%23697!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.3.jar%23696!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
```

Full log is included, I do have a whole bunch of other mods installed.

[latest.log](https://github.com/WayofTime/BloodMagic/files/12567988/latest.log)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.20.1-3.3.0-42
- Minecraft: 1.20.1
- Forge: 47.1.3

**Comment by wrincewind** [comment]
Does the crash still occur when you disable all other mods? (make a backup of your world first, for obvious reasons). 

if not, can you try a binary search (disable half your mods, see if it happens again, try the other half if not, repeat until you're down to just one mod) to see what's going on? 

Since you've mentioned you have a lot of other mods, I'd like to see if it's due to an interaction with one of them first. 

Cheers :¬)

**Comment by gardenappl** [comment]
Unfortunately it still crashes with only:
`bloodmagic-1.20.1-3.3.0-42.jar	Patchouli-1.20.1-81-FORGE.jar`
Same error, here's the log:
[latest.log](https://github.com/WayofTime/BloodMagic/files/12568007/latest.log)

**Comment by dphaldes** [comment]
I have created a PR with the fix. Thanks for reporting!
