### ISSUE TITLE
[1.20.1] Fortuna Extract voids drops

### ISSUE THREAD

**Issue by FoxMcloud5655** [WayofTime/BloodMagic#1974]
#### Issue Description:
Fortuna Extract applied to a tool voids drops until it's gone.  Server console spits out an error once or twice during this time related to Blood Magic and the Fortuna Extract.

#### What happens:
Fortuna Extract applied to tools voids drops and spits out an error in the console.

#### What you expected to happen:
The drops to be multiplied on top of the Fortune enchant already present on the tool.

#### Steps to reproduce:
1. Apply Fortuna Extract to a tool
2. Mine anything.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.3.1-43
- Minecraft: 1.20.1
- Forge: 47.1.3

Below is the truncated error in question:
```
Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@70879dd4, suppressing error
java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:origin>, <parameter minecraft:block_state>]
	at net.minecraft.world.level.storage.loot.LootParams$Builder.m_287235_(LootParams.java:132) ~[server-1.20.1-20230612.114412-srg.jar%23577!/:?]
	at wayoftime.bloodmagic.loot.GlobalLootModifier$FortuneModifier.doApply(GlobalLootModifier.java:132) ~[bloodmagic-1.20.1-3.3.1-43.jar%23367!/:1.20.1-3.3.1-43]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23582!/:?]
```

**Comment by WayofTime** [comment]
Thanks for the post and the log! Pushed a fix, and will create an update later.

**Comment by FoxMcloud5655** [comment]
Alright!  Now to test this out...
