### ISSUE TITLE
Odd traceback spamming my logs...

### ISSUE THREAD

**Issue by utoxin** [WayofTime/BloodMagic#199]
Bit of background: We were running 1.3.0-1, and one of my players summoned a demon invasion. It worked reasonably well, although his ritual never got replaced with the altar construct I've seen in other videos. And then I noticed that my logs were being flooded by your debug output, so I decided to update.

After the update to 1.3.0a-1, I'm getting a ton of stack traces thrown into my logs. One of them appears to be from Blood Magic, and occurs every few seconds:

[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.Exception: Stack trace
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at java.lang.Thread.dumpStack(Unknown Source)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:781)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:470)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_72964_e(World.java:419)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:39)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_72844_a(World.java:3352)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:81)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:85)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.ai.EntityAIWander.func_75249_e(SourceFile:41)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at WayofTime.alchemicalWizardry.common.entity.mob.EntityDemon.func_70636_d(EntityDemon.java:106)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at WayofTime.alchemicalWizardry.common.demonVillage.demonHoard.demon.EntityMinorDemonGrunt.func_70636_d(EntityMinorDemonGrunt.java:242)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at WayofTime.alchemicalWizardry.common.demonVillage.demonHoard.demon.EntityMinorDemonGrunt.func_70071_h_(EntityMinorDemonGrunt.java:260)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_72866_a(World.java:2070)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_72870_g(World.java:2034)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_72939_s(World.java:1887)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by utoxin** [comment]
If you need any additional information, please ask. I'm happy to help.

**Comment by utoxin** [comment]
Figured it out. There was an notice I was discounting as related that turned out to be triggering this somehow. I fixed that (by killing the entities) and this went away.

For reference the arrow error was:

[06:22:19] [Server thread/WARN]: Wrong location! EntityArrow['arrow'/67397, l='world', x=7055.28, y=9776.80, z=9765.81] (at 440, 610 instead of -8, 21)
