### ISSUE TITLE
[Error] Can't place player // Serverside exception // Related to spectral tiles

### ISSUE THREAD

**Issue by MaxWasUnavailable** [WayofTime/BloodMagic#2030]
#### Issue Description:
Players randomly can't join the server until (sometimes) a restart of the server resolves it. 

Relevant debug log snippet:

```
[15Mar2024 17:10:53.394] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "p_129203_" is null
        at net.minecraft.nbt.NbtUtils.m_129202_(NbtUtils.java:254) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at wayoftime.bloodmagic.common.tile.TileSpectral.serialize(TileSpectral.java:82) ~[bloodmagic-1.20.1-3.3.2-44.jar%23492!/:1.20.1-3.3.2-44]
        at wayoftime.bloodmagic.common.tile.base.TileBase.m_5995_(TileBase.java:132) ~[bloodmagic-1.20.1-3.3.2-44.jar%23492!/:1.20.1-3.3.2-44]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:152) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1261) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:892) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ChunkMap.sendSpiralChunkWatchPackets(ChunkMap.java:3617) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:3439) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1158) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:465) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1505) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1488) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:136) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:97) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:75) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:834) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:215) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23785!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

```

#### What happens:
Player tries to join, but gets "disconnected". The server's debug log reports blood magic's spectral tiles to be related to the issue.

#### What you expected to happen:
Player can join server.

#### Steps to reproduce:

1. Attempt to join server nearby someone who is playing with Blood Magic stuff
2. Get disconnected, with "can't place player" error on the server-side log

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: `bloodmagic-1.20.1-3.3.2-44`
- Minecraft: `1.20.1`
- Forge: `47.2.16`

**Comment by MaxWasUnavailable** [comment]
Likely to be related to https://github.com/WayofTime/BloodMagic/issues/2026

**Comment by wrincewind** [comment]
fixed by #2096 and #2140 - will close on the next release.
