### ISSUE TITLE
Casting simple spell with Glowstone + Zombie head causes server crash

### ISSUE THREAD

**Issue by the-vindex** [WayofTime/BloodMagic#233]
BloodMagic version: 1.3.0a-1.

java.lang.NoSuchMethodError: net.minecraft.world.World.func_72894_k(F)V
        at WayofTime.alchemicalWizardry.common.spell.simple.SpellLightningBolt.onOffensiveMeleeRightClick(SpellLightningBolt.java:68) ~[SpellLightningBolt.class:1.7.10-1.3.0a-1]
        at WayofTime.alchemicalWizardry.common.tileEntity.TEHomHeart.castSpell(TEHomHeart.java:56) ~[TEHomHeart.class:1.7.10-1.3.0a-1]
        at WayofTime.alchemicalWizardry.common.items.BlankSpell.func_77659_a(BlankSpell.java:79) ~[BlankSpell.class:1.7.10-1.3.0a-1]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
