### ISSUE TITLE
Crash that I cannot figure out what went wrong : / *spammy crashreport

### ISSUE THREAD

**Issue by Megachuggayoshi** [WayofTime/BloodMagic#270]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 3/4/15 3:43 PM
Description: Initializing game

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at WayofTime.alchemicalWizardry.common.demonVillage.tileEntity.TEDemonPortal.loadBuildingList(TEDemonPortal.java:1558)
	at WayofTime.alchemicalWizardry.AlchemicalWizardry.preInit(AlchemicalWizardry.java:491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at WayofTime.alchemicalWizardry.common.demonVillage.tileEntity.TEDemonPortal.loadBuildingList(TEDemonPortal.java:1558)
	at WayofTime.alchemicalWizardry.AlchemicalWizardry.preInit(AlchemicalWizardry.java:491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.9.4
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 348207648 bytes (332 MB) / 634912768 bytes (605 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 96 mods loaded, 96 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0RC2} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC2-195.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC3-56.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0RC2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC2-129.jar) Unloaded->Constructed->Pre-initialized
	BigReactors{0.4.1A} [Big Reactors] (BigReactors-0.4.1A.jar) Unloaded->Constructed->Pre-initialized
	AWWayofTime{v1.3.0b} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0b-3.jar) Unloaded->Constructed->Errored
	BuildCraft|Core{6.3.7} [BuildCraft] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.3.7} [BC Transport] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.3.7} [BC Silicon] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.3.7} [BC Builders] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.3.7} [BC Energy] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.3.7} [BC Factory] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.1.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.4.jar) Unloaded->Constructed->Pre-initialized
	MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized
	RedstoneArsenal{1.7.10R1.1.0RC2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar) Unloaded->Constructed->Pre-initialized
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-10.jar) Unloaded->Constructed->Pre-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized
	simplyjetpacks{1.3.2} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized
	ThermalDynamics{1.7.10R1.0.0RC2} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC2-77.jar) Unloaded->Constructed->Pre-initialized
	TiCTooltips{1.2.3} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{0.2.13.96} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.13.96.jar) Unloaded->Constructed->Pre-initialized
	taverns{2.2.1-0} [Village Taverns] (VillageTaverns-2.2.1-0.23.jar) Unloaded->Constructed->Pre-initialized
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized
	YALSM{2.1.3} [Yet Another Leather Smelting Mod] (Yet-Another-Leather-Smelting-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	CoFHCore: -[1.7.10]3.0.0RC2-195
	ThermalFoundation: -[1.7.10]1.0.0RC3-56
	ThermalExpansion: -[1.7.10]4.0.0RC2-129
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.0RC7-71
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: Lacking version information.
	NetherOres: -[1.7.10]2.3.0RC4-10
	ThermalDynamics: -[1.7.10]1.0.0RC2-77
	Stencil buffer state: Function set: ARB, pool: forge, bits: 2
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-8.28.30, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by WayofTime** [comment]
Try deleting config/BLoodMagic and try again.

**Comment by Megachuggayoshi** [comment]
Thank you,also there IS a recipe for the alchemical chemistry set for one shard of any kind (from thaumcraft) plus one stone equals a certain infused stone right? because there was in Agrarian skies but I don't know if that was custom or not
