### ISSUE TITLE
/help command error

### ISSUE THREAD

**Issue by ravendm5** [WayofTime/BloodMagic#341]
I just upgraded from version 1.3.2-1 to version 1.3.3-4 and the minecraft /help command started erroring whenever I try to run it.  Downgraded back to 1.3.2-1 and the command works again.  I am using Guide-API version 1.0.1-20.  This error occurred in both an existing world and a new world.

The error from the console: 

[16:44:21] [Server thread/ERROR]: Couldn't process command: 'help'
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(Unknown Source) ~[?:1.8.0-ea]
	at java.util.ComparableTimSort.mergeAt(Unknown Source) ~[?:1.8.0-ea]
	at java.util.ComparableTimSort.mergeCollapse(Unknown Source) ~[?:1.8.0-ea]
	at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.8.0-ea]
	at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0-ea]
	at java.util.Collections.sort(Unknown Source) ~[?:1.8.0-ea]
	at net.minecraft.command.CommandHelp.func_71534_d(SourceFile:84) ~[au.class:?]
	at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:38) ~[au.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[16:44:21] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by Arcaratus** [comment]
Shouldn't be anything on BM's side...

**Comment by ljfa-ag** [comment]
Mods breaking the help command seems to be a pretty common occurrence
Well, does anyone have the range of commits between 1.3.2-1 and 1.3.3-4 ?
