### ISSUE TITLE
Not saving LP using Windows

### ISSUE THREAD

**Issue by COM8** [WayofTime/BloodMagic#430]
Problem:
You can't create a file on a Windows pc like COM8/COM7/....* and BloodMagic try's to. My ingame name is COM8. So there is a problem. :(

Possible solution:
Don't use ingame names for this it would be better to use the UUID or something else .
So everybody can play again without problems. :D

Informations:
Minecraft: 1.7.10
Forge: forge-10.13.4.1492
BloodMagic: 1.7.10-1.3.3-13

Possible error-Log:
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: D:\Fabian\Documents\Curse\Minecraft\Instances\test\saves\New World\data\COM8.dat (Das System kann die angegebene Datei nicht finden)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.FileOutputStream.open(Native Method)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:92)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:838)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:802)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:106)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[23:29:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by WayofTime** [comment]
When does this occur? And I HIGHLY doubt it is because I am using your name, pretty sure that's the normal player.dat that MC creates for your character.

**Comment by TehNut** [comment]
Yup, that's the data file that Minecraft creates. If it were because of your name, you'd never be able to even create a world.

**Comment by Nincodedo** [comment]
I tried to make a file in Windows named COM8.dat. It stops you. http://i.imgur.com/NtlAhoO.png

**Comment by TehNut** [comment]
And again, this is a file generated by Minecraft. It has nothing to do with BloodMagic, really.

**Comment by Nincodedo** [comment]
How? The file is being created in the SoulNetworkhandler with the owner's name. https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/api/soulNetwork/SoulNetworkHandler.java

**Comment by WayofTime** [comment]
I'm creating a line in the file, if anything. Show the line in the handler that creates an actual file.

**Comment by WayofTime** [comment]
I think the main issue here is that this is a once-in-a-blue-moon occurance. Eventually I will change to using UUIDs, but in all seriousness this is something that I doubt anyone could have seen coming.

(That file is the saved data, yes)

**Comment by Nincodedo** [comment]
Agreed, I didn't even know COM8 and such were reserved file names.

**Comment by COM8** [comment]
@Nincodedo Yes Thaumcraft / Baubles have the same problem and I already reported it.
https://github.com/Azanor/thaumcraft/issues/1715
LogisticsPipes has the same problem.
https://github.com/RS485/LogisticsPipes/issues/775

**Comment by WayofTime** [comment]
I'm going to have to close this right now. I can assume that because you decided on the name COM8, you knew what you might get in to if a mod creates a file with your name. Therefore I am going to close this issue and EVENTUALLY rework this.
