### ISSUE TITLE
A Crash - Not sure what is causing it.

### ISSUE THREAD

**Issue by DPxKnightxZero** [WayofTime/BloodMagic#462]
at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at WayofTime.alchemicalWizardry.common.compress.StorageBlockCraftingRecipeAssimilator.areInputsIdentical(StorageBlockCraftingRecipeAssimilator.java:225)
	at WayofTime.alchemicalWizardry.common.compress.StorageBlockCraftingRecipeAssimilator.getIdenticalInputs(StorageBlockCraftingRecipeAssimilator.java:205)
	at WayofTime.alchemicalWizardry.common.compress.StorageBlockCraftingRecipeAssimilator.getPackingRecipe(StorageBlockCraftingRecipeAssimilator.java:164)
	at WayofTime.alchemicalWizardry.common.compress.StorageBlockCraftingRecipeAssimilator.getPackingRecipes(StorageBlockCraftingRecipeAssimilator.java:35)
	at WayofTime.alchemicalWizardry.common.compress.StorageBlockCraftingManager.addStorageBlockRecipes(StorageBlockCraftingManager.java:27)
	at WayofTime.alchemicalWizardry.AlchemicalWizardry.initCompressionHandlers(AlchemicalWizardry.java:1645)
	at WayofTime.alchemicalWizardry.AlchemicalWizardry.postInit(AlchemicalWizardry.java:1266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TehNut** [comment]
Maybe try providing the full log on Pastebin.

**Comment by DPxKnightxZero** [comment]
https://gist.github.com/DPxKnightxZero/78efdb49eab230c9706f

**Comment by WayofTime** [comment]
I've heard Forestry 4 is doing retarded stuff with their recipes, same with Dragon API. I have a handler that goes through recipes, and if they do stuff like null outputs or null Items, the thing will fail on my handler.

**Comment by DPxKnightxZero** [comment]
I think it may have been divine rpg and forestry XD

**Comment by DPxKnightxZero** [comment]
Honestly you might want to talk to the forestry team because they massively updated their API.

**Comment by TehNut** [comment]
Or you could just downgrade to a stable version of Forestry.

**Comment by DPxKnightxZero** [comment]
Way to ignore the issue XD

**Comment by TehNut** [comment]
Except it's not an issue? Forestry 4 is not compatible with anything that supports Forestry 3. It's also an issue on *their* end.

xxXXXXXdDDDDDDddddDDD
