### ISSUE TITLE
Blood Altar Crashes my Game

### ISSUE THREAD

**Issue by Ninjapope** [WayofTime/BloodMagic#474]
I'm using minecraft ver. 1.7.10 and the problem happened in both Blood Magic Versions 1.7.10-1.3.3-12 and 1.7.10-1.3.3-13
I was also using the Guide API 1.7.10-1.0.1-20
I'm using forge 1.7.10.13.2.1230
Whenever i try to place a Blood altar my game crashes
Here are both crash Reports
---- Minecraft Crash Report ----
// You're mean.

Time: 10/18/15 5:06 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.buildFluidList(TEAltar.java:906)
	at WayofTime.alchemicalWizardry.common.NewPacketHandler.getPacket(NewPacketHandler.java:981)
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145844_m(TEAltar.java:668)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.buildFluidList(TEAltar.java:906)
	at WayofTime.alchemicalWizardry.common.NewPacketHandler.getPacket(NewPacketHandler.java:981)
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145844_m(TEAltar.java:668)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)

-- Affected level --
Details:
	Level name: Copy of Test
	All players: 1 total; [EntityPlayerMP['gaurdiansphinx'/8, l='Copy of Test', x=-1153.50, y=4.00, z=439.50]]
	Chunk stats: ServerChunkCache: 1205 Drop: 0
	Level seed: 6081000692599972243
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1156,4,436), Chunk: (at 12,0,4 in -73,27; contains blocks -1168,0,432 to -1153,255,447), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 365 game time, 365 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 107115 (now: false), thunder time: 156231 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 177149744 bytes (168 MB) / 350527488 bytes (334 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['gaurdiansphinx'/8, l='Copy of Test', x=-1153.50, y=4.00, z=439.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 10/18/15 4:57 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.buildFluidList(TEAltar.java:906)
	at WayofTime.alchemicalWizardry.common.NewPacketHandler.getPacket(NewPacketHandler.java:981)
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145844_m(TEAltar.java:668)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.buildFluidList(TEAltar.java:906)
	at WayofTime.alchemicalWizardry.common.NewPacketHandler.getPacket(NewPacketHandler.java:981)
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145844_m(TEAltar.java:668)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)

-- Affected level --
Details:
	Level name: Blood Magic Creative
	All players: 1 total; [EntityPlayerMP['gaurdiansphinx'/157436, l='Blood Magic Creative', x=130.52, y=16.00, z=75.34]]
	Chunk stats: ServerChunkCache: 1135 Drop: 0
	Level seed: 1660196624
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (253,64,232), Chunk: (at 13,4,8 in 15,14; contains blocks 240,0,224 to 255,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 85616 game time, 85616 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 47108 (now: false), thunder time: 67631 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 214179272 bytes (204 MB) / 676315136 bytes (644 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['gaurdiansphinx'/157436, l='Blood Magic Creative', x=130.52, y=16.00, z=75.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TehNut** [comment]
Update Forge.

**Comment by Ninjapope** [comment]
That Fixed the problem thanks
