### ISSUE TITLE
Bound pick and activated redstone ore 

### ISSUE THREAD

**Issue by TOLoneWolf** [WayofTime/BloodMagic#506]
FTB Infinity Pack 2.1.2
BloodMagic-1.7.10-1.3.3-17

After using the bound picks right click to mine for a bit i would find areas that would disconnect me from the server. After looking around I finally notice that there was an activated redstone ore there glowing, removed it by mining the normal left click way and then i could right click without the disconnect happening.

Disconnect message on client: Internal Server Error
Error code from server console:
<code>[04:29:56] [Server thread/WARN]: Failed to handle packet for /IP_ADDRESS:PORT
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:201) ~[?:1.7.0_80]
	at WayofTime.alchemicalWizardry.common.ItemType.<init>(ItemType.java:23) ~[ItemType.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.ItemType.<init>(ItemType.java:40) ~[ItemType.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.ItemType.<init>(ItemType.java:45) ~[ItemType.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.common.items.BoundPickaxe.func_77659_a(BoundPickaxe.java:176) ~[BoundPickaxe.class:1.7.10-1.3.3-17]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[04:29:56] [Server thread/INFO]: TOLoneWolf lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[04:29:56] [Server thread/INFO]: TOLoneWolf left the game</code>

**Comment by Grath** [comment]
I'm also experiencing this bug - at least now I know the workaround of 'don't mine activated redstone'.

**Comment by Blue64** [comment]
that's one funky looking code tag lol to include the line returns, put the ``` ` ` ` ``` on it's own line
```
kinda
` ` `
like
this
` ` `
somewhat
```
except get rid of the spaces between the ``` ` ` ` ``` (because github doesn't like me typing it together)

**Comment by TehNut** [comment]
This is solved in the 1.8 builds.
