### ISSUE TITLE
Errors with AgriCraft

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [WayofTime/BloodMagic#564]
[19:31:12] [Server thread/INFO] [BloodMagic/AWWayofTime]: Loaded Harvestcraft Handlers!
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchMethodException: com.InfinityRaider.AgriCraft.blocks.BlockCrop.harvest(net.minecraft.world.World, int, int, int)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Class.getMethod(Class.java:1786)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at WayofTime.alchemicalWizardry.common.harvest.AgriCraftCropHarvestHandler.<init>(AgriCraftCropHarvestHandler.java:27)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at WayofTime.alchemicalWizardry.AlchemicalWizardry.postInit(AlchemicalWizardry.java:1316)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:497)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[19:31:12] [Server thread/INFO] [STDERR/AWWayofTime]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by TehNut** [comment]
What version of Agricraft do you have? I distinctly remember InfinityRaider re-adding that method after #499 with https://github.com/InfinityRaider/AgriCraft/commit/37d2018b15b7f023fc9f91c64265a940d48ade24.

**Comment by P3rf3ctXZer0** [comment]
I will check. [Universal]-AgriCraft-1.7.10-1.4.6-hotfix

**Comment by TehNut** [comment]
Hm. Now that I look back at it, we're _attempting_ to call `harvest(World world, int x, int y, int z)`. However, that hasn't existed since https://github.com/InfinityRaider/AgriCraft/commit/cfd166545d7d68ed97726974ecd23dc8b4a353df.

**Comment by P3rf3ctXZer0** [comment]
Glad I could assist you.

**Comment by TehNut** [comment]
@InfinityRaider - I absolutely hate to ask, but would it be possible to get that method back since the EntityPlayer can be null? I only ask because I know you're planning a new version.

**Comment by InfinityRaider** [comment]
What method precisely?

**Comment by TehNut** [comment]
You currently have `harvest(World, int, int, int, EntityPlayer)` and `harvest(World, int, int, int, EntityPlayer, TileEntityCrop)`. In the commit I linked above, you removed the `harvest(World, int, int, int)` one.

Since EntityPlayer can be null, I'm asking for the following to be (re)added to `BlockCrop`:

``` java
public boolean harvest(World world, int x, int y, int z) {
    return harvest (world, x, y, z, null, null);
}
```

**Comment by InfinityRaider** [comment]
Oh, I added the wrong method back , is that what you mean? Yeah sure I can do that.

**Comment by TehNut** [comment]
Awesome, thank you! \o/

**Comment by InfinityRaider** [comment]
https://github.com/InfinityRaider/AgriCraft/commit/e7983bf9bfc530cfaff00a38f1bc00a1601a2203
