### ISSUE TITLE
Game Crash when binding new Teleposition Focus to point.

### ISSUE THREAD

**Issue by AkioKasai** [WayofTime/BloodMagic#609]
It crashes the first time, every time, but if I relaunch the game it works after that. Every new one does the same thing.

Wasn't sure how to go about reporting this, but here's the crash report in question. If you need anything else from it or me, let me know.

```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at WayofTime.bloodmagic.item.ItemTelepositionFocus.setBlockPos(ItemTelepositionFocus.java:102)
    at WayofTime.bloodmagic.item.ItemTelepositionFocus.func_77659_a(ItemTelepositionFocus.java:61)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:152)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:433)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1520)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
--------------
-- Head --
Stacktrace:
    at WayofTime.bloodmagic.item.ItemTelepositionFocus.setBlockPos(ItemTelepositionFocus.java:102)
    at WayofTime.bloodmagic.item.ItemTelepositionFocus.func_77659_a(ItemTelepositionFocus.java:61)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:152)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:433)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1520)
```

**Comment by TehNut** [comment]
... i swear i tested this one.
