### ISSUE TITLE
Server crashing with BloodMagic-1.8.9-2.0.0-19 when restarting server with something in altar

### ISSUE THREAD

**Issue by shortybsd** [WayofTime/BloodMagic#672]
#### Issue Description:

Server crashing upon startup after leaving something in altar in MC v1.8.9.
Running BloodMagic-1.8.9-2.0.0-19
#### What happens:

Server crashes with the following error: http://pastebin.com/8ZQK8dvS
Server won't load when leaving something in the altar.
#### Steps to reproduce:
1. Put something in altar
2. Restart server.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.8.9-2.0.0-19
- Minecraft: 1.8.9
- Forge: forge-1.8.9-11.15.1.1764

**Comment by shortybsd** [comment]
In the latest.log this is what happens as the server is almost fully up and ready

[13:18:09] [Server thread/ERROR] [FML/]: Exception caught during firing event WayofTime.bloodmagic.api.event.AltarCraftedEvent@564e4071:
java.lang.NullPointerException
    at WayofTime.bloodmagic.util.handler.EventHandler.onAltarCrafted(EventHandler.java:279) ~[EventHandler.class:1.8.9-2.0.0-19]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_EventHandler_onAltarCrafted_AltarCraftedEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at WayofTime.bloodmagic.altar.BloodAltar.updateAltar(BloodAltar.java:455) [BloodAltar.class:1.8.9-2.0.0-19]
    at WayofTime.bloodmagic.altar.BloodAltar.update(BloodAltar.java:382) [BloodAltar.class:1.8.9-2.0.0-19]
    at WayofTime.bloodmagic.tile.TileAltar.func_73660_a(TileAltar.java:49) [TileAltar.class:1.8.9-2.0.0-19]
    at net.minecraft.world.World.func_72939_s(World.java:1718) [adm.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545) [le.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
[13:18:09] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[13:18:09] [Server thread/ERROR] [FML/]: 0: NORMAL
[13:18:09] [Server thread/ERROR] [FML/]: 1: ASM: WayofTime.bloodmagic.util.handler.EventHandler@591c2c0d onAltarCrafted(LWayofTime/bloodmagic/api/event/AltarCraftedEvent;)V
[13:18:09] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save LU

**Comment by TehNut** [comment]
#651

**Comment by shortybsd** [comment]
When is a fix expected? The last i saw was "Will fix tomorrow", 16 days ago.

**Comment by TehNut** [comment]
"Will fix tomorrow" meant in code. The fix is expected as soon as the build button is pressed. Getting some final fixes in place as build 20 will be the final build for 1.8.9.

**Comment by shortybsd** [comment]
Gotcha, thanks for the heads up! Just MCEdit out the altar til then?
