### ISSUE TITLE
[1.7.10] Blood Altar crashes my game

### ISSUE THREAD

**Issue by silascs** [WayofTime/BloodMagic#704]
#### Issue Description:

When I place a blood altar, my game crashes after 10-20 seconds. Saw someone who had a similar issue but i tried what solved it for them (downloading a newer forge build) and it did not work.
Here is the error message:
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 4/3/16 9:25 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: com/cricketcraft/chisel/api/carving/CarvingUtils
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.CompatChecks.checkChiselBlock(CompatChecks.java:14)
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkRuneSpecials(UpgradedAltars.java:365)
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkAltarIsValid(UpgradedAltars.java:171)
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.isAltarValid(UpgradedAltars.java:34)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.checkAndSetAltar(TEAltar.java:763)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.startCycle(TEAltar.java:734)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145845_h(TEAltar.java:528)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: com.cricketcraft.chisel.api.carving.CarvingUtils
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.CompatChecks.checkChiselBlock(CompatChecks.java:14)
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkRuneSpecials(UpgradedAltars.java:365)
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.checkAltarIsValid(UpgradedAltars.java:171)
    at WayofTime.alchemicalWizardry.common.bloodAltarUpgrade.UpgradedAltars.isAltarValid(UpgradedAltars.java:34)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.checkAndSetAltar(TEAltar.java:763)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.startCycle(TEAltar.java:734)
    at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145845_h(TEAltar.java:528)

-- Block entity being ticked --
Details:
    Name: containerAltar // WayofTime.alchemicalWizardry.common.tileEntity.TEAltar
    Block type: ID #440 (tile.bloodAltar // WayofTime.alchemicalWizardry.common.block.BlockAltar)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-299,46,2160), Chunk: (at 5,2,0 in -19,135; contains blocks -304,0,2160 to -289,255,2175), Region: (-1,4; contains chunks -32,128 to -1,159, blocks -512,0,2048 to -1,255,2559)
    Actual block type: ID #440 (tile.bloodAltar // WayofTime.alchemicalWizardry.common.block.BlockAltar)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

---
#### Affected Versions:
- BloodMagic: 1.3.3-17
- Minecraft: 1.7.10
- Forge: 10.13.4.1614 and 10.13.4.1558

**Comment by TehNut** [comment]
Use the updated Chisel. http://minecraft.curseforge.com/projects/chisel

**Comment by silascs** [comment]
Thanks
