### ISSUE TITLE
cant load mod (1.7.10)

### ISSUE THREAD

**Issue by kitarak** [WayofTime/BloodMagic#756]
#### What happens:

it crashed while loading my mods

Time: 5/25/16 5:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: amerifrance.guideapi.pages.PageIRecipe.<init>(Lnet/minecraft/item/crafting/IRecipe;Lamerifrance/guideapi/api/abstraction/IRecipeRenderer;)V
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: amerifrance.guideapi.pages.PageIRecipe.<init>(Lnet/minecraft/item/crafting/IRecipe;Lamerifrance/guideapi/api/abstraction/IRecipeRenderer;)V
    at WayofTime.alchemicalWizardry.common.book.BloodMagicGuide.getOrbPageForRecipe(BloodMagicGuide.java:52)
    at WayofTime.alchemicalWizardry.common.book.BloodMagicGuide.registerArchitectBook(BloodMagicGuide.java:81)
    at WayofTime.alchemicalWizardry.common.book.BloodMagicGuide.registerGuide(BloodMagicGuide.java:36)
    at WayofTime.alchemicalWizardry.AlchemicalWizardry.registerBMBook(AlchemicalWizardry.java:1342)
    at WayofTime.alchemicalWizardry.AlchemicalWizardry.postInit(AlchemicalWizardry.java:1282)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 162206304 bytes (154 MB) / 460013568 bytes (438 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 19 mods loaded, 19 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   Automagy{0.28.2} [Automagy](Automagy-1.7.10-0.28.2.jar) 
    UCHIJ   BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHIE   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHIJ   Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHIJ   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJ   ForbiddenMagic{1.7.10-0.574} [Forbidden Magic](Forbidden Magic-1.7.10-0.574.jar) 
    UCHIJ   guideapi{1.7.10-1.0-9} [Guide-API](Guide-API-1.7.10-1.0-9.jar) 
    UCHIJ   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJ   Mystcraft{0.12.3.02} [Mystcraft](mystcraft-1.7.10-0.12.3.02.jar) 
    UCHIJ   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJ   ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar) 
    UCHIJ   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJ   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

i have tried using older versions of the 1.7.10 version of the mod, reinstalling forge, and uninstalling all other mods, but so far nothing seems to work :( i apologize if this is known issue, but I've been looking around for a few days on various forums and haven't been able to find anything.

**Comment by kitarak** [comment]
ugh, my guide api was out of date, was wrestling with it on and off for days, then figured it out less then 10 min after open the thread. forgive me.

**Comment by WayofTime** [comment]
No charge! :P
