### ISSUE TITLE
Server Crash On Join

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [WayofTime/BloodMagic#782]
#### Issue Description:

Issue is on a server and a modpack, I work closely with the modpack developer as an admin on his test server and we believe this does link to Bloodmagic.
#### What happens: Everything was fine, i was the only one on and suddenly server crashes. I join back in after starting again and instantly crashes once more. Crashes are common due to techreborn and usually stops the second time, however, it did not. So we checked the logs and noticed that the ritual of Forsaken Souls was causing an issue, We 'believe' that what's causing this issue is that we ran out of demonic will in the grand tartaric gem while in the Demon Cruicible as the ritual was active. Note that i had 9 Demon Crystallizers and 4 Demon Crucibles around the ritual area, the cruicibles filled with grand tartaric gems

This is the crash lines we believe point to blood magic:

**Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at net.minecraft.tileentity.TileEntity.func_145832_p(TileEntity.java:142)
    at WayofTime.bloodmagic.tile.TileDemonCrystal.growCrystalWithWillAmount(TileDemonCrystal.java:114)
    at WayofTime.bloodmagic.ritual.RitualForsakenSoul.performRitual(RitualForsakenSoul.java:149)
    at WayofTime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:199)
    at WayofTime.bloodmagic.tile.TileMasterRitualStone.func_73660_a(TileMasterRitualStone.java:79)
    at net.minecraft.world.World.func_72939_s(World.java:1797)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Thread.java:745)*\* 

and here is the full crash log:
http://pastebin.com/7A9S5LXD

and here is an image of what my setup was:
http://imgur.com/KcL5kZf
#### What you expected to happen:

Does not apply? Obviously not to crash.
#### Steps to reproduce:

Cannot be reproduced, I attempted to do this in single player to see if i would crash but it may be that it is server side crash? if thats a thing, however here are the steps of the setup you see in the Imgur picture.
1. Ritual of forsaken souls
2. Place crystallizers, demon crucibles, one pylon, 4 grand gems full
3. let time run its course and suddenly crash.
...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-42
- Minecraft: 1.9.4
- Forge: 12.17.0.1940

**Comment by WayofTime** [comment]
Seems to be a NPE in the tile... Going to do a workaround.

**Comment by EPIICTHUNDERCAT** [comment]
worked the magic, thank you Way!
