### ISSUE TITLE
[1.10]v1.9.4Crash When Activating Ritual

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [WayofTime/BloodMagic#838]
#### Issue Description:

This is in a modpack, however, this doesn't seem to be connected to any other mod. 
#### Steps to reproduce:
1. Activate ritual
2. crash?
3. Retried and got the same crash, other rituals like crusher and magnetism worked so it seems to be well of suffering. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.2-48
- Minecraft: 1.10
- Forge: 2000

here is the report:

java.lang.ClassCastException: refinedstorage.tile.TileCable cannot be cast to WayofTime.bloodmagic.api.ritual.IRitualStone$Tile
    at WayofTime.bloodmagic.api.util.helper.RitualHelper.isRuneType(RitualHelper.java:126)
    at WayofTime.bloodmagic.api.util.helper.RitualHelper.checkValidRitual(RitualHelper.java:102)
    at WayofTime.bloodmagic.api.util.helper.RitualHelper.getValidRitual(RitualHelper.java:61)
    at WayofTime.bloodmagic.block.BlockRitualController.func_180639_a(BlockRitualController.java:67)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by EPIICTHUNDERCAT** [comment]
wait just re read the log, its seems like something from refined storage seems to be messing with it. ill removed it and try again. (sorry dont want to post useless things)

**Comment by EPIICTHUNDERCAT** [comment]
seems like removing the refined storage cables fixed it, but this is still an issue, i reported it the other mod author as well 👍

**Comment by EPIICTHUNDERCAT** [comment]
Refined storage mod dev said this, "Blood magic issue, they are casting my cable to a tile of blood magic. "

**Comment by TehNut** [comment]
The only way for us to get that far is if their tile tells us that it has our capability. https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/api/util/helper/RitualHelper.java#L125

I do not see how this is our issue.

**Comment by WayofTime** [comment]
If this was a pure BM issue, then it would happen with ALL Tile Entities.

**Comment by raoulvdberge** [comment]
Well, I'm not telling that cables are a Blood Magic capability either:
https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/refinedstorage/tile/TileNode.java#L156-L168

**Comment by WayofTime** [comment]
So the question is: if both of our codes are right, where is the screw up?

**Comment by raoulvdberge** [comment]
It truly is a mystery.

**Comment by WayofTime** [comment]
Only reason that this wouldn't work, I think... is if both of the capabilities were somehow null.

**Comment by WayofTime** [comment]
Where do you register your capability?

**Comment by raoulvdberge** [comment]
```
public final class RefinedStorageCapabilities {
    @CapabilityInject(INetworkNode.class)
    public static final Capability<INetworkNode> NETWORK_NODE_CAPABILITY = null;
}
```

**Comment by WayofTime** [comment]
May also need this, though @TehNut was the one to implement this:
https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/proxy/CommonProxy.java#L38

**Comment by TehNut** [comment]
I did not. That was Alex with #641

**Comment by WayofTime** [comment]
Mah bad. But looking at the capabilities that Forge adds (CapabilityItemHandler.ITEM_HANDLER_CAPABILITY and CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY) it seems that it is necessary.

**Comment by TehNut** [comment]
AFAIK, CababilityInject is to get an instance of the cap. Not to register it.

**Comment by EPIICTHUNDERCAT** [comment]
this is very exciting to watch. I applaud you all, and praise you all.

**Comment by raoulvdberge** [comment]
I got rid of the capability alltogether in dev branch, so you can close this.

**Comment by WayofTime** [comment]
Thanks for your time! ^_^

**Comment by raoulvdberge** [comment]
No problem :)
