### ISSUE TITLE
Cannot do damage to mobs

### ISSUE THREAD

**Issue by xannor** [WayofTime/BloodMagic#934]
#### Issue Description:

Get the following after updating to 2.1.0-64 when trying to attack a mob:

[19:39:00] [Server thread/FATAL]: Error executing task  
java.util.concurrent.ExecutionException: java.lang.NullPointerException  
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_72]  
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_72]  
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]  
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]  
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]  
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]  
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]  
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]  
Caused by: java.lang.NullPointerException  
        at WayofTime.bloodmagic.util.Utils.hasUUID(Utils.java:1184) ~[Utils.class:1.9.4-2.1.0-64]  
        at WayofTime.bloodmagic.util.Utils.getUUID(Utils.java:1189) ~[Utils.class:1.9.4-2.1.0-64]  
        at WayofTime.bloodmagic.item.armour.ItemLivingArmour.hasLivingArmour(ItemLivingArmour.java:531) ~[ItemLivingArmour.class:1.9.4-2.1.0-64]  
        at WayofTime.bloodmagic.item.armour.ItemLivingArmour.getUpgrade(ItemLivingArmour.java:496) ~[ItemLivingArmour.class:1.9.4-2.1.0-64]  
        at WayofTime.bloodmagic.util.handler.event.GenericHandler.onEntityHurt(GenericHandler.java:158) ~[GenericHandler.class:1.9.4-2.1.0-64]  
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_174_GenericHandler_onEntityHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?]  
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]  
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]  
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:502) ~[ForgeHooks.class:?]  
        at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1296) ~[sf.class:?]  
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:890) ~[sf.class:?]  
        at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:64) ~[wc.class:?]  
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293) ~[zs.class:?]  
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1226) ~[lu.class:?]  
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1040) ~[me.class:?]  
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]  
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]  
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]  
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_72]  
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_72]  
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]  
        ... 5 more  
#### What happens:

Nothing
#### What you expected to happen:

Damage
#### Steps to reproduce:
1. make stone sword
2. attack mob
3. ...
   no profit
   ---
   #### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0-64
- Minecraft: 1.10.2
- Forge: 2094

**Comment by WayofTime** [comment]
@_@
