### ISSUE TITLE
[1.10] Probably Waila's fault. NPE crash occasionally while placing lighted mimic blocks. 

### ISSUE THREAD

**Issue by MrNinja93** [WayofTime/BloodMagic#949]
#### Issue Description:

Almost guaranteed to be WAILA's side ([Report](https://bitbucket.org/ProfMobius/waila/issues/285/null-pointer-exception-crash-to-desktop)) but just in-case reporting it here too (feel free to close if nothing to do with blood magics side), NPE crash when placing lighted mimic blocks. 

**Stacktrace from one of the crashes**

```
-- Head --
Thread: Client thread
Stacktrace:
    at WayofTime.bloodmagic.compat.waila.provider.DataProviderMimic.getWailaStack(DataProviderMimic.java:24)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:153)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:96)
    at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:65)
    at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:36)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickRender(WailaTickHandler.java:54)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_731_WailaTickHandler_tickRender_RenderTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
```
#### What happens:

Crash to desktop when placing lighted mimic blocks (had two crashes in placing 30 blocks)
#### What you expected to happen:

No crashes
#### Steps to reproduce:
1. Waila + blood magic installed
2. Go crazy placing lighted mimic blocks in blocks (probably other mimics too)
3. Enjoy crashiness
#### Crash logs:

http://pastebin.com/caaLA3RY
http://pastebin.com/UrJatMpk

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 63
- Waila-1.7.0-B3_1.9.4
- Minecraft: 1.10.2
- Forge: 2094

**Comment by TehNut** [comment]
Actually I think that's our (mine specifically) fault.

**Comment by MrNinja93** [comment]
Somewhat glad if it is Blood Magic's side, doubt a fix would come Waila's side with its apparent abandonment.
